(() => {
  'use strict';
  const STORAGE_KEY = 'kg-math-mission-progress-v1';
  const qs = s => document.querySelector(s);
  const el = id => document.getElementById(id);
  const clamp = (n,a,b) => Math.max(a, Math.min(b,n));
  const rand = (a,b) => Math.floor(Math.random()*(b-a+1))+a;
  const shuffle = arr => { const a=[...arr]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; };
  const uid = () => Math.random().toString(36).slice(2,9);

  const weeks = [
    {title:'Numbers 0–5', goal:'Connect numerals, quantities, and accurate counting.', days:[
      ['Number Hunt','Recognize numerals 0–5',['numeral','numeral','numeral','numeral','numeral']],
      ['Count It','Count sets accurately and name the total',['count','count','count','count','count']],
      ['Build It','Make a requested quantity',['build','build','build','build','build']],
      ['Same Amount','Understand quantity stays the same when objects move',['conservation','conservation','count','conservation','count']]
    ]},
    {title:'Numbers 0–10', goal:'Extend counting and numeral-quantity matching through 10.', days:[
      ['Number Hunt 0–10','Recognize numerals out of order',['numeral10','numeral10','numeral10','numeral10','numeral10']],
      ['Count Any Arrangement','Count sets in different layouts',['count10','count10','count10','count10','count10']],
      ['Match Number & Set','Move between symbols and quantities',['build10','count10','numeral10','build10','count10']],
      ['Mixed 0–10','Combine recognition, counting, and building',['numeral10','count10','build10','count10','numeral10']]
    ]},
    {title:'Subitizing & Comparing', goal:'See small quantities quickly and compare amounts.', days:[
      ['Quick Look 1–3','Recognize tiny groups without counting',['subitize3','subitize3','subitize3','subitize3','subitize3']],
      ['Quick Look 1–5','Recognize common dot patterns',['subitize5','subitize5','subitize5','subitize5','subitize5']],
      ['More, Fewer, Same','Compare groups of objects',['compareGroups','compareGroups','compareGroups','compareGroups','compareGroups']],
      ['Compare Numbers','Connect written numerals to greater quantities',['compareNumbers','compareNumbers','compareNumbers','compareGroups','compareNumbers']]
    ]},
    {title:'Sequence & ±1', goal:'Understand number order, one more, and one less.', days:[
      ['Missing Number','Complete a number sequence',['sequence','sequence','sequence','sequence','sequence']],
      ['Before & After','Find neighboring numbers',['beforeAfter','beforeAfter','beforeAfter','beforeAfter','beforeAfter']],
      ['One More','Know that the next number is one more',['oneMore','oneMore','oneMore','oneMore','oneMore']],
      ['One Less','Know that removing one gives the previous number',['oneLess','oneLess','oneLess','oneLess','oneLess']]
    ]},
    {title:'Make & Break Numbers', goal:'Compose and decompose numbers as parts and wholes.', days:[
      ['Make 5','Build 5 in different ways',['make5','make5','make5','make5','make5']],
      ['Missing Part','Find the hidden part of 5',['hidden5','hidden5','hidden5','hidden5','hidden5']],
      ['Make 6–8','Compose larger numbers from parts',['compose68','compose68','compose68','compose68','compose68']],
      ['Make 9–10','Compose numbers close to ten',['compose910','compose910','compose910','compose910','compose910']]
    ]},
    {title:'Addition & Subtraction', goal:'Model joining and separating quantities before relying on symbols.', days:[
      ['Add Within 5','Join two groups and find the total',['add5','add5','add5','add5','add5']],
      ['Subtract Within 5','Take away and find how many remain',['sub5','sub5','sub5','sub5','sub5']],
      ['Picture Equations','Connect models to equations',['equation5','equation5','equation5','equation5','equation5']],
      ['Story Problems','Solve simple join/separate stories',['story5','story5','story5','story5','story5']]
    ]},
    {title:'Teen Numbers', goal:'Understand 11–20 as ten and some more ones.', days:[
      ['11–13','Recognize and build early teen numbers',['teenEarly','teenEarly','teenEarly','teenEarly','teenEarly']],
      ['14–16','See teen numbers as 10 + ones',['teenMid','teenMid','teenMid','teenMid','teenMid']],
      ['17–20','Extend the ten-and-ones structure',['teenLate','teenLate','teenLate','teenLate','teenLate']],
      ['Teen Number Mix','Move between numeral, model, and decomposition',['teenMixed','teenMixed','teenMixed','teenMixed','teenMixed']]
    ]},
    {title:'Mixed Mastery', goal:'Apply number sense while maintaining geometry and measurement vocabulary.', days:[
      ['Number Sense Check','Review core number skills',['numeral10','subitize5','oneMore','compareNumbers','count10']],
      ['Operations Check','Review parts, addition, and subtraction',['hidden5','add5','sub5','equation5','story5']],
      ['Shapes & Measurement','Name shapes and compare measurable attributes',['shape','shape','measure','measure','sortCount']],
      ['Final Mission','Mixed independent mastery check',['teenMixed','sequence','compareGroups','add5','shape','count10']]
    ]}
  ];

  const state = {
    view:'home', week:0, day:0, round:0, attempts:0, correct:0, stars:0, locked:false,
    prompt:'', hint:'', nextReady:false, timer:null, deferredInstall:null
  };

  function blankProgress(){
    const lessons={}; for(let w=0;w<8;w++) for(let d=0;d<4;d++) lessons[`${w}-${d}`]={complete:false,correct:0,attempts:0,stars:0,bestPct:0,completedAt:null};
    return {lessons,totalCorrect:0,totalAttempts:0,totalStars:0,lastCompleted:null,streak:0};
  }
  function loadProgress(){ try{ const raw=localStorage.getItem(STORAGE_KEY); if(!raw) return blankProgress(); const p=JSON.parse(raw); return {...blankProgress(),...p,lessons:{...blankProgress().lessons,...(p.lessons||{})}}; }catch{return blankProgress();} }
  let progress=loadProgress();
  function saveProgress(){ try{localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));}catch{} renderHomeStats(); }

  function showView(name){ ['homeView','lessonView','parentView'].forEach(id=>el(id).classList.remove('active')); el(name+'View').classList.add('active'); state.view=name; window.scrollTo({top:0,behavior:'smooth'}); }
  function speak(text){ if(!('speechSynthesis' in window)) return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.rate=.86; u.pitch=1.04; u.lang='en-US'; speechSynthesis.speak(u); }
  function clearTimer(){ if(state.timer){clearTimeout(state.timer);state.timer=null;} }
  function setFeedback(text,type=''){ const f=el('feedback'); f.textContent=text; f.className='feedback'+(type?' '+type:''); }
  function showHint(){ setFeedback(state.hint || 'Take your time and try again.','hint'); }
  function recordAttempt(ok){ state.attempts++; progress.totalAttempts++; if(ok){state.correct++;state.stars++;progress.totalCorrect++;progress.totalStars++; state.locked=true; setFeedback('Correct! Nice work.','good'); el('nextBtn').classList.remove('hidden'); el('hintBtn').classList.add('hidden');} else {setFeedback('Not yet. Try one more time.','bad'); el('hintBtn').classList.remove('hidden');} saveProgress(); updateLessonHeader(); }
  function makeChoiceGrid(options,onPick,textMode=false){ const g=document.createElement('div'); g.className='choice-grid'; options.forEach(opt=>{const b=document.createElement('button');b.type='button';b.className='choice'+(textMode?' smalltext':'');b.textContent=opt.label ?? opt; b.addEventListener('click',()=>{if(state.locked)return;onPick(opt.value ?? opt,b);});g.appendChild(b);}); return g; }
  function numericOptions(correct,min,max,count=4){ const all=[];for(let i=min;i<=max;i++)all.push(i);let opts=shuffle(all).slice(0,Math.min(count,all.length));if(!opts.includes(correct)){opts[0]=correct;opts=shuffle(opts);}return opts; }
  function dots(n,ghost=0){ const wrap=document.createElement('div'); wrap.className='dots'; for(let i=0;i<n;i++){const d=document.createElement('span');d.className='dot';wrap.appendChild(d);} for(let i=0;i<ghost;i++){const d=document.createElement('span');d.className='dot ghost';wrap.appendChild(d);} return wrap; }
  function setPrompt(text,hint){ state.prompt=text;state.hint=hint||''; el('promptText').textContent=text; }
  function stageReset(){ clearTimer(); state.locked=false; state.nextReady=false; el('activityStage').innerHTML=''; setFeedback(''); el('nextBtn').classList.add('hidden'); el('hintBtn').classList.add('hidden'); }

  const activities = {
    numeral(max=5){ const target=rand(0,max); setPrompt(`Tap the number ${target}.`,`Say the number sequence slowly and look for ${target}.`); const s=el('activityStage'); const big=document.createElement('div');big.className='prompt-big';big.innerHTML=`Find <span style="color:var(--accent)">${target}</span>`;s.appendChild(big); s.appendChild(makeChoiceGrid(numericOptions(target,0,max,Math.min(6,max+1)),v=>recordAttempt(v===target))); },
    numeral10(){activities.numeral(10);},
    count(max=5){ const target=rand(1,max); setPrompt('Count the dots. How many are there?','Touch each dot one time. The last number you say tells how many.'); const s=el('activityStage');s.appendChild(dots(target));s.appendChild(makeChoiceGrid(numericOptions(target,1,max,4),v=>recordAttempt(v===target))); },
    count10(){activities.count(10);},
    build(max=5){ const target=rand(1,max); setPrompt(`Build ${target}. Tap exactly ${target} circles.`,`Count the dark circles and stop when you say ${target}.`); const s=el('activityStage'); const big=document.createElement('div');big.className='prompt-big';big.textContent=`Build ${target}`;s.appendChild(big); const frame=document.createElement('div');frame.className='ten-frame'; const cells=[]; for(let i=0;i<10;i++){const b=document.createElement('button');b.type='button';b.className='ten-cell';b.setAttribute('aria-label',`counter ${i+1}`);b.addEventListener('click',()=>{b.classList.toggle('on');});cells.push(b);frame.appendChild(b);} s.appendChild(frame); const check=document.createElement('button');check.type='button';check.className='btn primary';check.style.marginTop='18px';check.textContent='Check my set';check.addEventListener('click',()=>{if(state.locked)return;recordAttempt(cells.filter(c=>c.classList.contains('on')).length===target);});s.appendChild(check); },
    build10(){activities.build(10);},
    conservation(){ const target=rand(2,5); setPrompt('Do both groups have the same number?','Count both groups. Spacing does not change how many objects there are.'); const s=el('activityStage'); const same=Math.random()<.5; const other=same?target:clamp(target+(Math.random()<.5?-1:1),1,5); const wrap=document.createElement('div');wrap.className='compare-wrap'; const a=document.createElement('div');a.className='compare-box';a.appendChild(dots(target)); const vs=document.createElement('div');vs.className='vs';vs.textContent='and'; const b=document.createElement('div');b.className='compare-box'; const dd=dots(other); dd.style.gap=same?'28px':'7px';b.appendChild(dd);wrap.append(a,vs,b);s.appendChild(wrap); s.appendChild(makeChoiceGrid([{label:'Yes, same',value:true},{label:'No, different',value:false}],v=>recordAttempt(v===same),true)); },
    subitize(max=5){ const target=rand(1,max); setPrompt('Quick look. How many dots did you see?','Picture the group in your mind. Counting is okay while you are learning.'); const s=el('activityStage'); const holder=document.createElement('div');holder.appendChild(dots(target));s.appendChild(holder); state.timer=setTimeout(()=>{holder.innerHTML='<div class="muted">Now choose the number you saw.</div>';s.appendChild(makeChoiceGrid(numericOptions(target,1,max,4),v=>recordAttempt(v===target)));},1100); },
    subitize3(){activities.subitize(3);},subitize5(){activities.subitize(5);},
    compareGroups(){ let a=rand(1,8),b=rand(1,8); if(Math.random()<.2)b=a; const ask=shuffle(['more','fewer'])[0]; setPrompt(`Which group has ${ask}?`,`Count each group, then compare the totals.`); const s=el('activityStage'); const wrap=document.createElement('div');wrap.className='compare-wrap'; const L=document.createElement('button');L.type='button';L.className='compare-box';L.appendChild(dots(a)); const mid=document.createElement('div');mid.className='vs';mid.textContent='vs'; const R=document.createElement('button');R.type='button';R.className='compare-box';R.appendChild(dots(b));wrap.append(L,mid,R);s.appendChild(wrap); const equal=a===b; const correct=equal?'same':(ask==='more'?(a>b?'left':'right'):(a<b?'left':'right')); const options=[{label:'Left',value:'left'},{label:'Right',value:'right'}]; if(equal)options.push({label:'Same',value:'same'}); s.appendChild(makeChoiceGrid(options,v=>recordAttempt(v===correct),true)); },
    compareNumbers(){ let a=rand(0,10),b=rand(0,10); while(b===a)b=rand(0,10); const ask=shuffle(['greater','smaller'])[0]; setPrompt(`Which number is ${ask}?`,`If needed, build each number with objects and compare the groups.`); const correct=ask==='greater'?Math.max(a,b):Math.min(a,b); const s=el('activityStage'); const wrap=document.createElement('div');wrap.className='compare-wrap'; [a,b].forEach((n,i)=>{if(i) {const v=document.createElement('div');v.className='vs';v.textContent='or';wrap.appendChild(v);} const btn=document.createElement('button');btn.type='button';btn.className='compare-box number-card';btn.textContent=n;btn.addEventListener('click',()=>{if(!state.locked)recordAttempt(n===correct);});wrap.appendChild(btn);});s.appendChild(wrap); },
    sequence(){ const start=rand(0,6),miss=rand(1,3); const seq=[start,start+1,start+2,start+3,start+4]; const correct=seq[miss]; setPrompt('What number is missing?','Count forward one number at a time.'); const s=el('activityStage'); const row=document.createElement('div');row.className='sequence';seq.forEach((n,i)=>{const x=document.createElement('div');x.className='seq-item'+(i===miss?' blank':'');x.textContent=i===miss?'?':n;row.appendChild(x);});s.appendChild(row);s.appendChild(makeChoiceGrid(numericOptions(correct,Math.max(0,correct-2),Math.min(10,correct+2),4),v=>recordAttempt(v===correct))); },
    beforeAfter(){ const n=rand(2,9),after=Math.random()<.5; const correct=after?n+1:n-1; setPrompt(`What number comes ${after?'after':'before'} ${n}?`,`Say the counting sequence around ${n}.`); const s=el('activityStage'); const big=document.createElement('div');big.className='number-card';big.textContent=n;s.appendChild(big);s.appendChild(makeChoiceGrid(numericOptions(correct,0,10,4),v=>recordAttempt(v===correct))); },
    oneMore(){ const n=rand(0,9),correct=n+1;setPrompt(`What is one more than ${n}?`,'Imagine adding one object to the group.');const s=el('activityStage'); if(n===0){const z=document.createElement('div');z.className='number-card';z.textContent='0';s.appendChild(z);}else{s.appendChild(dots(n));} s.appendChild(makeChoiceGrid(numericOptions(correct,0,10,4),v=>recordAttempt(v===correct))); },
    oneLess(){ const n=rand(1,10),correct=n-1;setPrompt(`What is one less than ${n}?`,'Imagine taking one object away.');const s=el('activityStage');s.appendChild(dots(n));s.appendChild(makeChoiceGrid(numericOptions(correct,0,10,4),v=>recordAttempt(v===correct))); },
    make5(){ const part=rand(0,5),correct=5-part;setPrompt(`${part} and how many more make 5?`,'Build 5 counters. Separate out the part you already know.');const s=el('activityStage');const e=document.createElement('div');e.className='equation';e.textContent=`${part} + ? = 5`;s.appendChild(e);s.appendChild(makeChoiceGrid(numericOptions(correct,0,5,4),v=>recordAttempt(v===correct))); },
    hidden5(){ const hidden=rand(1,4),shown=5-hidden;setPrompt(`There are 5 altogether. You can see ${shown}. How many are hidden?`,'Count up from the part you can see until you reach 5.');const s=el('activityStage');const wrap=document.createElement('div');wrap.className='compare-wrap';const a=document.createElement('div');a.className='compare-box';a.appendChild(dots(shown));const mid=document.createElement('div');mid.className='vs';mid.textContent='+';const b=document.createElement('div');b.className='compare-box';b.innerHTML='<div class="number-card">?</div>';wrap.append(a,mid,b);s.appendChild(wrap);s.appendChild(makeChoiceGrid(numericOptions(hidden,0,5,4),v=>recordAttempt(v===hidden))); },
    composeRange(min,max){ const target=rand(min,max),part=rand(1,target-1),correct=target-part;setPrompt(`${part} and how many more make ${target}?`,`Count on from ${part} until you reach ${target}.`);const s=el('activityStage');const e=document.createElement('div');e.className='equation';e.textContent=`${part} + ? = ${target}`;s.appendChild(e);s.appendChild(makeChoiceGrid(numericOptions(correct,0,Math.min(10,target),4),v=>recordAttempt(v===correct))); },
    compose68(){activities.composeRange(6,8);},compose910(){activities.composeRange(9,10);},
    add5(){ const a=rand(0,4),b=rand(0,5-a),correct=a+b;setPrompt(`${a} and ${b} more. How many altogether?`,'Join the two groups, then count the total.');const s=el('activityStage');const wrap=document.createElement('div');wrap.className='compare-wrap';const L=document.createElement('div');L.className='compare-box';L.appendChild(dots(a||0));if(a===0)L.textContent='0';const mid=document.createElement('div');mid.className='vs';mid.textContent='+';const R=document.createElement('div');R.className='compare-box';R.appendChild(dots(b||0));if(b===0)R.textContent='0';wrap.append(L,mid,R);s.appendChild(wrap);s.appendChild(makeChoiceGrid(numericOptions(correct,0,5,4),v=>recordAttempt(v===correct))); },
    sub5(){ const a=rand(1,5),b=rand(0,a),correct=a-b;setPrompt(`${a} take away ${b}. How many are left?`,'Start with the whole group and remove the ones being taken away.');const s=el('activityStage');const frame=document.createElement('div');frame.className='ten-frame';for(let i=0;i<10;i++){const c=document.createElement('div');c.className='ten-cell';if(i<a)c.classList.add(i>=a-b?'removed':'on');frame.appendChild(c);}s.appendChild(frame);s.appendChild(makeChoiceGrid(numericOptions(correct,0,5,4),v=>recordAttempt(v===correct))); },
    equation5(){ const add=Math.random()<.5;if(add){const a=rand(0,4),b=rand(0,5-a),correct=a+b;setPrompt(`Solve: ${a} + ${b} = ?`,'You may draw or count objects to solve it.');const s=el('activityStage');const e=document.createElement('div');e.className='equation';e.textContent=`${a} + ${b} = ?`;s.appendChild(e);s.appendChild(makeChoiceGrid(numericOptions(correct,0,5,4),v=>recordAttempt(v===correct)));}else{const a=rand(1,5),b=rand(0,a),correct=a-b;setPrompt(`Solve: ${a} − ${b} = ?`,'Start with the first number and take away the second number.');const s=el('activityStage');const e=document.createElement('div');e.className='equation';e.textContent=`${a} − ${b} = ?`;s.appendChild(e);s.appendChild(makeChoiceGrid(numericOptions(correct,0,5,4),v=>recordAttempt(v===correct)));}},
    story5(){ const add=Math.random()<.5; const s=el('activityStage'); if(add){const a=rand(1,3),b=rand(1,5-a),c=a+b;setPrompt(`You have ${a} toy cars. You get ${b} more. How many toy cars do you have now?`,'Act out the story: start with the first group, then add the new group.');const p=document.createElement('div');p.className='story';p.textContent=state.prompt;s.appendChild(p);s.appendChild(makeChoiceGrid(numericOptions(c,0,5,4),v=>recordAttempt(v===c)));}else{const a=rand(2,5),b=rand(1,a),c=a-b;setPrompt(`There are ${a} ducks. ${b} swim away. How many ducks are left?`,'Act out the story: start with all the ducks, then take some away.');const p=document.createElement('div');p.className='story';p.textContent=state.prompt;s.appendChild(p);s.appendChild(makeChoiceGrid(numericOptions(c,0,5,4),v=>recordAttempt(v===c)));}},
    teen(min,max){ const target=rand(min,max),ones=target-10; const mode=shuffle(['name','ones'])[0]; const s=el('activityStage'); if(mode==='name'){setPrompt('How many are shown?','A full ten-frame is 10. Count the extra ones.');const frames=document.createElement('div');frames.style.display='grid';frames.style.gap='14px';const full=document.createElement('div');full.className='ten-frame';for(let i=0;i<10;i++){const c=document.createElement('div');c.className='ten-cell on';full.appendChild(c);}const extra=document.createElement('div');extra.className='ten-frame';for(let i=0;i<10;i++){const c=document.createElement('div');c.className='ten-cell';if(i<ones)c.classList.add('on');extra.appendChild(c);}frames.append(full,extra);s.appendChild(frames);s.appendChild(makeChoiceGrid(numericOptions(target,min,max,4),v=>recordAttempt(v===target)));}else{setPrompt(`${target} is 10 and how many more?`,'The teen number tells you there is one ten and some extra ones.');const e=document.createElement('div');e.className='equation';e.textContent=`${target} = 10 + ?`;s.appendChild(e);s.appendChild(makeChoiceGrid(numericOptions(ones,0,10,4),v=>recordAttempt(v===ones)));}},
    teenEarly(){activities.teen(11,13);},teenMid(){activities.teen(14,16);},teenLate(){activities.teen(17,20);},teenMixed(){activities.teen(11,20);},
    shape(){ const shapes=[['circle','Circle'],['square','Square'],['rectangle','Rectangle'],['triangle','Triangle'],['hexagon','Hexagon']]; const pick=shapes[rand(0,shapes.length-1)];setPrompt('What shape is this?','Look at the number of sides and corners.');const s=el('activityStage');const box=document.createElement('div');box.className='shape-stage';const sh=document.createElement('div');sh.className=`shape ${pick[0]}`;box.appendChild(sh);s.appendChild(box);const shapeChoices=shuffle(shapes.filter(x=>x[1]!==pick[1])).slice(0,3); shapeChoices.push(pick); s.appendChild(makeChoiceGrid(shuffle(shapeChoices).map(x=>({label:x[1],value:x[1]})),v=>recordAttempt(v===pick[1]),true)); },
    measure(){ const ask=Math.random()<.5?'longer':'shorter'; let a=rand(90,180),b=rand(90,180); while(Math.abs(a-b)<25)b=rand(90,180); const correct=ask==='longer'?(a>b?'left':'right'):(a<b?'left':'right'); setPrompt(`Which bar is ${ask}?`,'Compare where each bar begins and ends.'); const s=el('activityStage');const bars=document.createElement('div');bars.className='bars';[['left',a],['right',b]].forEach(([side,w])=>{const btn=document.createElement('button');btn.type='button';btn.className='bar-choice';const bar=document.createElement('div');bar.className='bar';bar.style.width=w+'px';btn.appendChild(bar);btn.addEventListener('click',()=>{if(!state.locked)recordAttempt(side===correct);});bars.appendChild(btn);});s.appendChild(bars); },
    sortCount(){ const symbols=['●','▲','■']; const target=rand(0,2); const items=[]; for(let i=0;i<9;i++)items.push(symbols[rand(0,2)]); const count=items.filter(x=>x===symbols[target]).length; setPrompt(`How many ${['circles','triangles','squares'][target]} are there?`,'Look only for the requested shape and count each one once.');const s=el('activityStage');const scene=document.createElement('div');scene.className='sort-scene';items.forEach(x=>{const it=document.createElement('div');it.className='sort-item';it.textContent=x;scene.appendChild(it);});s.appendChild(scene);s.appendChild(makeChoiceGrid(numericOptions(count,0,9,4),v=>recordAttempt(v===count))); }
  };

  function resolveActivity(name){ const fn=activities[name]; if(!fn) throw new Error(`Unknown activity: ${name}`); return fn; }
  function currentLesson(){return weeks[state.week].days[state.day];}
  function updateLessonHeader(){ const [name,goal,rounds]=currentLesson(); el('lessonEyebrow').textContent=`Week ${state.week+1} • Day ${state.day+1}`;el('lessonTitle').textContent=name;el('lessonGoal').textContent=goal;el('lessonScore').textContent=`⭐ ${state.stars}`;el('roundLabel').textContent=`Round ${Math.min(state.round+1,rounds.length)} of ${rounds.length}`;el('lessonBar').style.width=`${Math.round(100*state.round/rounds.length)}%`; }
  function renderRound(){ stageReset(); updateLessonHeader(); const rounds=currentLesson()[2]; if(state.round>=rounds.length){finishLesson();return;} const act=resolveActivity(rounds[state.round]); act(); }
  function startLesson(w,d){ state.week=w;state.day=d;state.round=0;state.attempts=0;state.correct=0;state.stars=0; showView('lesson'); renderRound(); }
  function nextRound(){ state.round++; renderRound(); }
  function finishLesson(){ stageReset(); const key=`${state.week}-${state.day}`; const pct=state.attempts?Math.round(100*state.correct/state.attempts):0; const rec=progress.lessons[key]; const wasComplete=rec.complete; rec.complete=true;rec.correct=state.correct;rec.attempts=state.attempts;rec.stars=state.stars;rec.bestPct=Math.max(rec.bestPct||0,pct);rec.completedAt=new Date().toISOString(); if(!wasComplete){ const today=new Date().toISOString().slice(0,10); const last=progress.lastCompleted; if(last){ const diff=Math.round((Date.parse(today+'T00:00:00Z')-Date.parse(last+'T00:00:00Z'))/86400000); progress.streak=diff===1?(progress.streak||0)+1:diff===0?(progress.streak||1):1; }else progress.streak=1; progress.lastCompleted=today; }
    saveProgress(); el('lessonBar').style.width='100%'; el('roundLabel').textContent='Lesson complete'; el('promptText').textContent='Mission complete'; const s=el('activityStage'); const mastery=pct>=90?'Mastered':pct>=80?'Advance with review':pct>=70?'Repeat for fluency':'Reteach at an easier range'; s.innerHTML=`<div style="text-align:center"><div style="font-size:4rem">🏅</div><div class="prompt-big" style="margin:6px 0">${pct}% accuracy</div><div style="font-weight:900;font-size:1.25rem">${mastery}</div><p class="muted">${state.correct} correct across ${state.attempts} attempts • ${state.stars} stars</p></div>`; const home=document.createElement('button');home.type='button';home.className='btn primary';home.textContent='Back to lessons';home.addEventListener('click',()=>{renderHome();showView('home');});s.appendChild(home); speak('Great job. You finished the math mission.'); }

  function renderHome(){ const grid=el('weekGrid');grid.innerHTML=''; weeks.forEach((week,w)=>{const card=document.createElement('section');card.className='week-card card';const done=week.days.filter((_,d)=>progress.lessons[`${w}-${d}`].complete).length;card.innerHTML=`<div class="eyebrow">Week ${w+1}</div><h3>${week.title}</h3><p class="muted">${week.goal}</p>`;const list=document.createElement('div');list.className='lesson-list';week.days.forEach((day,d)=>{const rec=progress.lessons[`${w}-${d}`];const b=document.createElement('button');b.type='button';b.className='lesson-row'+(rec.complete?' complete':'');b.innerHTML=`<span class="day">DAY ${d+1}</span><span class="name">${day[0]}</span><span class="status">${rec.complete?`${rec.bestPct}% ✓`:'Start'}</span>`;b.addEventListener('click',()=>startLesson(w,d));list.appendChild(b);});card.appendChild(list);const foot=document.createElement('div');foot.className='week-progress';foot.textContent=`${done}/4 lessons complete`;card.appendChild(foot);grid.appendChild(card);});renderHomeStats(); }
  function renderHomeStats(){ const completed=Object.values(progress.lessons).filter(x=>x.complete).length; el('overallPct').textContent=Math.round(100*completed/32)+'%';el('overallBar').style.width=(100*completed/32)+'%'; }
  function renderParent(){ const completed=Object.values(progress.lessons).filter(x=>x.complete).length;el('statLessons').textContent=`${completed}/32`;el('statAccuracy').textContent=progress.totalAttempts?Math.round(100*progress.totalCorrect/progress.totalAttempts)+'%':'—';el('statStreak').textContent=progress.streak||0;el('statStars').textContent=progress.totalStars||0; const wrap=el('parentTableWrap'); let html='<table class="progress-table"><thead><tr><th>Week</th><th>Completed</th><th>Avg. best accuracy</th><th>Decision</th></tr></thead><tbody>';weeks.forEach((week,w)=>{const recs=week.days.map((_,d)=>progress.lessons[`${w}-${d}`]);const done=recs.filter(r=>r.complete);const avg=done.length?Math.round(done.reduce((n,r)=>n+(r.bestPct||0),0)/done.length):0;let cls='low',decision='Not enough data';if(done.length){if(avg>=90){cls='good';decision='Secure / advance';}else if(avg>=80){cls='mid';decision='Advance + review';}else if(avg>=70){cls='mid';decision='Repeat';}else{cls='low';decision='Reteach';}}html+=`<tr><td><strong>Week ${w+1}: ${week.title}</strong></td><td>${done.length}/4</td><td>${done.length?avg+'%':'—'}</td><td><span class="badge ${cls}">${decision}</span></td></tr>`;});html+='</tbody></table>';wrap.innerHTML=html; }

  el('backBtn').addEventListener('click',()=>{clearTimer();renderHome();showView('home');});
  el('parentBackBtn').addEventListener('click',()=>{renderHome();showView('home');});
  el('parentBtn').addEventListener('click',()=>{renderParent();showView('parent');});
  el('speakBtn').addEventListener('click',()=>speak(state.prompt||'Math mission'));
  el('hintBtn').addEventListener('click',showHint);
  el('nextBtn').addEventListener('click',nextRound);
  el('resetBtn').addEventListener('click',()=>{if(confirm('Reset all saved Math Mission progress on this device?')){progress=blankProgress();saveProgress();renderParent();renderHome();}});
  el('installBtn').addEventListener('click',async()=>{ if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;}else{el('installModal').classList.remove('hidden');} });
  el('closeInstall').addEventListener('click',()=>el('installModal').classList.add('hidden'));
  el('installModal').addEventListener('click',e=>{if(e.target===el('installModal'))el('installModal').classList.add('hidden');});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;});

  renderHome(); showView('home');
  if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
