(()=>{'use strict';
const $=id=>document.getElementById(id),A=(w=44)=>`<i class="ans" style="width:${w}px"></i>`,D=(n,c='')=>n?`<span class="dots ${c}" aria-label="${n} dots">${'<i></i>'.repeat(n)}</span>`:'<span class="empty">0 objects</span>',C=v=>`<span class="choice">${v}</span>`,T=n=>`<span class="ten">${Array.from({length:10},(_,i)=>`<i class="${i<n?'on':''}"></i>`).join('')}</span>`,B=(a,b)=>`<span class="bond"><i class="bt">5</i><i class="bl l"></i><i class="bl r"></i><i class="bp l">${a??''}</i><i class="bp r">${b??''}</i></span>`;
const meta=[['Trace & Write 0-5','Numbers 0-5'],['Count & Write 0-5','Counting'],['Match Number to Set 0-5','Number matching'],['Same Amount?','Quantity'],['Trace & Write 0-10','Numbers 0-10'],['Count & Circle 0-10','Counting'],['More, Fewer, or Same','Compare'],['Quick Look 1-5','Subitizing'],['Missing Numbers 0-10','Sequence'],['Before & After','Sequence'],['One More','+1'],['One Less','-1'],['Make 5','Compose'],['Number Bonds to 5','Part-whole'],['Make 10','Compose'],['Addition Within 5','Addition'],['Subtraction Within 5','Subtraction'],['Story Problems Within 5','Application'],['Teen Numbers','Base ten'],['Mixed Kindergarten Review','Review']];
const sh=(n,title,skill,inst,work)=>`<section class="sheet"><div class="head"><div><h2>Worksheet ${n}: ${title}</h2><p>${skill}</p></div><div class="nd"><label>Name <i></i></label><label>Date <i></i></label></div></div><div class="inst">${inst}</div><div class="work">${work}</div><footer><span>Math Mission - paper practice</span><span>Parent check: ____ / ____</span></footer></section>`;
function sheet(n){let w='',inst='',t=meta[n-1][0],s=meta[n-1][1];
switch(n){
case 1:inst='Trace each number, then write it two times by yourself.';w=Array.from({length:6},(_,x)=>`<div class="trace-row"><span class="trace">${x} ${x} ${x}</span><i class="line"></i><i class="line"></i>${D(x,'tiny')}</div>`).join('');break;
case 2:{inst='Count each set. Write the number in the box.';let a=[3,1,5,2,4,0,5,3];w=`<div class="two">${a.map((x,i)=>`<div class="card"><b>${i+1}.</b>${D(x)}${A()}</div>`).join('')}</div>`;break;}
case 3:{inst='Draw a line from each number to the set that shows the same amount.';let a=[3,0,5,2,1,4];w=`<div class="match"><div>${a.map((_,i)=>`<div class="match-num">${i}</div>`).join('')}</div><div>${a.map(x=>`<div class="match-set">${D(x)}</div>`).join('')}</div></div>`;break;}
case 4:{inst='Count both groups. Circle SAME if they have the same amount. Circle DIFFERENT if they do not.';let a=[[4,4],[3,5],[2,2],[5,4],[1,1],[4,3]];w=a.map((x,i)=>`<div class="cmp"><b>${i+1}.</b><div class="groups">${D(x[0])}${D(x[1])}</div><div class="yn">○ SAME &nbsp; ○ DIFFERENT</div></div>`).join('');break;}
case 5:inst='Trace each number once. Then write it on the line.';w=`<div class="two">${Array.from({length:11},(_,x)=>`<div class="trace10"><span class="trace" style="letter-spacing:0">${x}</span><i class="line" style="width:100px"></i>${x?D(x,'tiny'):''}</div>`).join('')}</div>`;break;
case 6:{inst='Count the dots. Circle the correct number.';let a=[6,2,9,4,7,10,5,8];w=`<div class="two">${a.map((x,i)=>`<div class="card" style="grid-template-columns:24px 1fr"><b>${i+1}.</b><div>${D(x,'sm')}<div class="choices">${[Math.max(0,x-1),x,Math.min(10,x+1)].map(C).join('')}</div></div></div>`).join('')}</div>`;break;}
case 7:{inst='Follow the direction for each row.';let a=[['Circle the group with MORE.',3,5],['Circle the group with FEWER.',6,2],['Are these the SAME amount?',4,4],['Circle the group with MORE.',7,5],['Are these the SAME amount?',3,4],['Circle the group with FEWER.',8,6]];w=a.map((x,i)=>`<div class="cmp"><b>${i+1}. ${x[0]}</b><div class="groups"><span class="box">${D(x[1],'sm')}</span><span class="box">${D(x[2],'sm')}</span></div>${x[0].includes('SAME')?'<div class="yn">○ YES &nbsp; ○ NO</div>':''}</div>`).join('');break;}
case 8:{inst='Look at each dot pattern. Write how many you see. Try to know it without counting one-by-one.';let a=[1,4,3,5,2,4,5,3,1,2];w=`<div class="two">${a.map(x=>`<div class="quick">${D(x)}<b>=</b>${A()}</div>`).join('')}</div>`;break;}
case 9:{inst='Write the missing numbers.';let a=[[0,1,null,3,4,null],[null,2,3,null,5,6],[4,null,6,7,null,9],[5,6,null,8,9,null],[10,null,8,null,6,5],[3,null,5,null,7,null],[null,1,null,3,null,5],[6,null,8,null,10]];w=a.map((r,i)=>`<div class="seq"><b>${i+1}.</b>${r.map(x=>x==null?A(42):`<span class="seqnum">${x}</span>`).join('')}</div>`).join('');break;}
case 10:{inst='Write the number that comes BEFORE and the number that comes AFTER.';let a=[2,5,8,4,7,9,3,6];w=a.map((x,i)=>`<div class="before"><b>${i+1}.</b><span class="labeled">BEFORE ${A(50)}</span><span class="center">${x}</span><span class="labeled">AFTER ${A(50)}</span></div>`).join('');break;}
case 11:{inst='Write the number that is ONE MORE.';let a=[0,3,6,1,8,4,5,2,7,9];w=`<div class="two">${a.map(x=>`<div class="eq"><span>${x} + 1 = ${A()}</span>${D(x,'tiny')}</div>`).join('')}</div>`;break;}
case 12:{inst='Write the number that is ONE LESS.';let a=[1,4,7,2,9,5,6,3,8,10];w=`<div class="two">${a.map(x=>`<div class="eq"><span>${x} - 1 = ${A()}</span>${D(x,'tiny')}</div>`).join('')}</div>`;break;}
case 13:{inst='Each row needs 5 dots. Draw more dots to MAKE 5, then write how many you added.';let a=[0,1,2,3,4,2,1,3];w=a.map((x,i)=>`<div class="make"><b>${i+1}.</b><span class="five">${Array.from({length:5},(_,j)=>`<i class="od ${j<x?'on':''}"></i>`).join('')}</span><span>I added ${A(38)} dots.</span></div>`).join('');break;}
case 14:{inst='Complete each number bond. The two parts make 5.';let a=[[0,null],[1,null],[2,null],[null,2],[4,null],[null,4],[3,null],[null,1]];w=`<div class="two">${a.map((x,i)=>`<div class="bondwrap"><b>${i+1}.</b>${B(x[0],x[1])}</div>`).join('')}</div>`;break;}
case 15:{inst='Count the filled dots. Write how many MORE are needed to make 10.';let a=[6,3,8,5,7,4];w=`<div class="two">${a.map((x,i)=>`<div class="make10"><b>${i+1}.</b>${T(x)}<span>${x} + ${A(38)} = 10</span></div>`).join('')}</div>`;break;}
case 16:{inst='Add. You may use the dots to help.';let a=[[1,2],[2,2],[3,1],[0,4],[2,3],[1,4],[3,2],[4,1]];w=`<div class="two">${a.map(x=>`<div class="op"><div>${D(x[0],'tiny')} <b>+</b> ${D(x[1],'tiny')}</div><div>${x[0]} + ${x[1]} = ${A()}</div></div>`).join('')}</div>`;break;}
case 17:{inst='Subtract. Cross out dots if it helps.';let a=[[3,1],[5,2],[4,1],[2,2],[5,1],[4,3],[3,2],[5,4]];w=`<div class="two">${a.map(x=>`<div class="op"><div>${D(x[0],'tiny')}</div><div>${x[0]} - ${x[1]} = ${A()}</div></div>`).join('')}</div>`;break;}
case 18:{inst='Solve each story. Draw a picture if you want, then write the answer.';let a=['Mila has 2 apples. She gets 1 more. How many apples now?','There are 5 ducks. 2 swim away. How many ducks are left?','3 blocks are on the rug. 2 more are added. How many blocks?','There are 4 cookies. 1 is eaten. How many cookies are left?','1 butterfly lands by 3 butterflies. How many butterflies?','5 toy cars are parked. 4 drive away. How many are left?'];w=a.map((x,i)=>`<div class="story"><b>${i+1}.</b><span>${x}</span><span class="draw">DRAW</span>${A()}</div>`).join('');break;}
case 19:{inst='Count ten and some more. Write the teen number and the extra ones.';let a=[11,14,17,12,16,19];w=`<div class="two">${a.map((x,i)=>`<div class="teen"><b>${i+1}.</b>${T(10)}${D(x-10,'tiny')}<div>Number: ${A()} &nbsp; 10 + ${A(38)}</div></div>`).join('')}</div>`;break;}
case 20:inst='Show what you know. Work carefully and do each problem by yourself.';w=`<div class="mixed"><b>1. Count the dots:</b>${D(7,'sm')}${A()}</div><div class="mixed"><b>2. Write the number after 6:</b>${A()}</div><div class="mixed"><b>3. Write the number before 5:</b>${A()}</div><div class="mixed"><b>4. Circle the group with MORE:</b><span class="boxed">${D(3,'tiny')}</span><span class="boxed">${D(5,'tiny')}</span></div><div class="mixed"><b>5. Quick look:</b>${D(4)}<span>How many?</span>${A()}</div><div class="mixed"><b>6. One more than 8 is</b>${A()}</div><div class="mixed"><b>7. 2 +</b>${A()}<b>= 5</b></div><div class="mixed"><b>8. 3 + 2 =</b>${A()}</div><div class="mixed"><b>9. 5 - 1 =</b>${A()}</div><div class="mixed"><b>10. 10 + 4 =</b>${A()}</div><div class="mixed"><b>11. Circle the triangle:</b><i class="shape circle"></i><i class="shape tri"></i><i class="shape sq"></i></div><div class="mixed"><b>12. Circle the LONGER line:</b><i class="hline short"></i><i class="hline long"></i></div>`;break;
}
return sh(n,t,s,inst,w)}
const sel=$('wsSelect'),grid=$('pickGrid'),pages=$('pages');meta.forEach((m,i)=>{sel.insertAdjacentHTML('beforeend',`<option value="${i+1}">Worksheet ${i+1}: ${m[0]}</option>`);grid.insertAdjacentHTML('beforeend',`<button type="button" class="pick" data-n="${i+1}"><strong>${i+1}. ${m[0]}</strong><span>${m[1]}</span></button>`)});
function show(n){pages.innerHTML=sheet(Number(n));sel.value=String(n);pages.scrollIntoView({behavior:'smooth',block:'start'})}grid.addEventListener('click',e=>{let b=e.target.closest('[data-n]');if(b)show(b.dataset.n)});sel.addEventListener('change',()=>show(sel.value));$('printOne').addEventListener('click',()=>window.print());$('printAll').addEventListener('click',()=>{pages.innerHTML=Array.from({length:20},(_,i)=>sheet(i+1)).join('');setTimeout(()=>window.print(),50)});window.addEventListener('afterprint',()=>show(sel.value));show(1);
})();
