(()=>{'use strict';
const $=id=>document.getElementById(id),A=(w=44)=>`<i class="ans" style="width:${w}px"></i>`,D=(n,c='')=>n?`<span class="dots ${c}" aria-label="${n} dots">${'<i></i>'.repeat(n)}</span>`:'<span class="empty">0 objects</span>',C=v=>`<span class="choice">${v}</span>`;
const meta=[['Trace & Write 0–5','K.CC.3'],['Count Sets to 10','K.CC.4a–b / K.CC.5'],['One-to-One Counting','K.CC.4a'],['Last Number Tells How Many','K.CC.4b'],['Same Number, New Layout','K.CC.4b'],['One More','K.CC.4c'],['Count Forward to 25','K.CC.2'],['Count by Tens to 100','K.CC.1b'],['Missing Numbers to 25','K.CC.1a / K.CC.2'],['More, Fewer, Equal','K.CC.6'],['Position Words','K.G.1'],['2D Shape Hunt','K.G.2–3'],['3D Shape Hunt','K.G.2–3'],['Shape Clues','K.G.4'],['Build Bigger Shapes','K.G.5–6'],['Length & Weight','K.MD.1'],['Measurement Words','K.MD.1'],['Model a Joining Story','K.OA.1'],['Model a Separating Story','K.OA.1'],['Term 1 Mastery Review','Current Term 1']];
const sh=(n,title,skill,inst,work)=>`<section class="sheet"><div class="head"><div><h2>Worksheet ${n}: ${title}</h2><p>${skill} • Harrison County Term 1</p></div><div class="nd"><label>Name <i></i></label><label>Date <i></i></label></div></div><div class="inst">${inst}</div><div class="work">${work}</div><footer><span>Math Mission • current-term paper practice</span><span>Parent check: ____ / ____</span></footer></section>`;
function sheet(n){let w='',inst='',t=meta[n-1][0],s=meta[n-1][1];switch(n){
case 1:inst='Trace each numeral, then write it two times by yourself.';w=Array.from({length:6},(_,x)=>`<div class="trace-row"><span class="trace">${x} ${x} ${x}</span><i class="line"></i><i class="line"></i>${D(x,'tiny')}</div>`).join('');break;
case 2:{inst='Touch each dot once while counting. Write how many.';let a=[3,7,1,5,9,2,8,4,10,6];w=`<div class="two">${a.map((x,i)=>`<div class="card"><b>${i+1}.</b>${D(x,'sm')}${A()}</div>`).join('')}</div>`;break;}
case 3:{inst='Draw one line from each object to one counting mark. Then write the total.';let a=[4,6,3,8,5,7];w=a.map((x,i)=>`<div class="cmp"><b>${i+1}.</b><div class="groups"><span class="box">${D(x,'sm')}</span><span class="box">${'| '.repeat(x)}</span></div><div>Total: ${A()}</div></div>`).join('');break;}
case 4:{inst='Count each set. Circle the number word you should say LAST.';let a=[2,5,4,7,3,6];w=a.map((x,i)=>`<div class="cmp"><b>${i+1}.</b>${D(x,'sm')}<div class="choices">${[Math.max(1,x-1),x,Math.min(10,x+1)].map(C).join('')}</div></div>`).join('');break;}
case 5:{inst='Count both groups. Circle SAME if moving the dots did not change how many.';let a=[[4,4],[6,6],[3,5],[7,7],[5,4],[2,2]];w=a.map((x,i)=>`<div class="cmp"><b>${i+1}.</b><div class="groups">${D(x[0],'sm')}${D(x[1],'sm')}</div><div class="yn">○ SAME &nbsp; ○ DIFFERENT</div></div>`).join('');break;}
case 6:{inst='Draw ONE more dot. Then write the new total.';let a=[1,4,6,2,8,5,3,7];w=`<div class="two">${a.map(x=>`<div class="op"><div>${D(x,'sm')} + one more</div><div>New total: ${A()}</div></div>`).join('')}</div>`;break;}
case 7:{inst='Count forward. Write the number that comes next.';let a=[3,8,12,17,20,5,14,23,9,19];w=`<div class="two">${a.map(x=>`<div class="eq"><span>${x}, ${A(48)}</span></div>`).join('')}</div>`;break;}
case 8:{inst='Fill in the missing numbers while counting by tens.';let rows=[[10,20,null,40,50],[30,null,50,60,70],[60,70,null,90,100],[10,null,30,null,50]];w=rows.map((r,i)=>`<div class="seq"><b>${i+1}.</b>${r.map(x=>x==null?A(48):`<span class="seqnum">${x}</span>`).join('')}</div>`).join('');break;}
case 9:{inst='Write the missing numbers. Stay within 1–25.';let rows=[[1,2,null,4,5],[6,null,8,9,null],[11,12,null,14,15],[16,null,18,null,20],[21,22,null,24,25],[4,5,6,null,8],[13,null,15,16,null],[19,20,null,22,23]];w=rows.map((r,i)=>`<div class="seq"><b>${i+1}.</b>${r.map(x=>x==null?A(42):`<span class="seqnum">${x}</span>`).join('')}</div>`).join('');break;}
case 10:{inst='Count both groups. Follow the direction.';let a=[['Circle MORE',3,6],['Circle FEWER',7,4],['Circle EQUAL if the same',5,5],['Circle MORE',8,6],['Circle FEWER',2,5],['Circle EQUAL if the same',4,3]];w=a.map((x,i)=>`<div class="cmp"><b>${i+1}. ${x[0]}</b><div class="groups"><span class="box">${D(x[1],'sm')}</span><span class="box">${D(x[2],'sm')}</span></div>${x[0].includes('EQUAL')?'<div class="yn">○ EQUAL &nbsp; ○ NOT EQUAL</div>':''}</div>`).join('');break;}
case 11:{inst='Circle the position word that completes each sentence.';let a=[['The star is ___ the box.','above',['above','heavy','circle']],['The ball is ___ the chair.','below',['below','square','long']],['The dog is ___ the tree.','beside',['beside','ten','light']],['The cat is ___ the chair.','behind',['behind','triangle','short']],['The child is ___ the line.','in front of',['in front of','cylinder','five']]];w=a.map((x,i)=>`<div class="mixed"><b>${i+1}. ${x[0]}</b><div class="choices">${x[2].map(C).join('')}</div></div>`).join('');break;}
case 12:{inst='Name each flat (2D) shape.';let a=[['○','circle'],['□','square'],['△','triangle'],['▭','rectangle'],['⬡','hexagon'],['△','triangle'],['○','circle'],['□','square']];w=`<div class="two">${a.map((x,i)=>`<div class="card"><b>${i+1}.</b><span style="font-size:48px">${x[0]}</span>${A(90)}</div>`).join('')}</div>`;break;}
case 13:{inst='Write the solid (3D) shape name: sphere, cube, cylinder, or cone.';let a=[['⚽','sphere'],['🧊','cube'],['🥫','cylinder'],['🍦','cone'],['⚽','sphere'],['🥫','cylinder']];w=`<div class="two">${a.map((x,i)=>`<div class="card"><b>${i+1}.</b><span style="font-size:42px">${x[0]}</span>${A(95)}</div>`).join('')}</div>`;break;}
case 14:{inst='Use sides, corners, curves, and faces to answer.';let q=[['A triangle has how many sides?','3'],['Which has no corners: circle or square?','circle'],['A hexagon has how many sides?','6'],['Which solid rolls easily: sphere or cube?','sphere'],['Which has 4 sides: square or triangle?','square'],['Which solid has two flat round faces?','cylinder']];w=q.map((x,i)=>`<div class="mixed"><b>${i+1}. ${x[0]}</b>${A(90)}</div>`).join('');break;}
case 15:{inst='Draw the smaller shapes you could join to make the larger shape.';let q=['Make a rectangle from 2 squares.','Make a square from 2 triangles.','Make a larger triangle from smaller triangles.','Make a larger rectangle from smaller rectangles.'];w=q.map((x,i)=>`<div class="story"><b>${i+1}. ${x}</b><span class="draw">DRAW HERE</span></div>`).join('');break;}
case 16:{inst='Circle the measurable attribute.';let q=[['pencil',['length','name','favorite']],['backpack',['weight','owner','picture']],['book',['length','story','color']],['rock',['weight','sound','letter']]];w=q.map((x,i)=>`<div class="mixed"><b>${i+1}. ${x[0]}:</b><div class="choices">${x[1].map(C).join('')}</div></div>`).join('');break;}
case 17:{inst='Use a measurement word to complete each sentence.';let q=['A school bus is very ____.','A feather is very ____.','A pencil can be ____ or short.','A full backpack may be ____.','A child can be ____ or short.'];w=q.map((x,i)=>`<div class="mixed"><b>${i+1}. ${x}</b>${A(90)}</div>`).join('');w+=`<div class="inst">Word bank: long • tall • heavy • light • short</div>`;break;}
case 18:{inst='Do NOT solve with an equation. Draw a picture that MODELS each joining story.';let q=['2 birds are on a fence. 1 more bird joins.','3 blocks are on the rug. 2 more blocks join the group.','1 car is parked. 3 more cars arrive.','2 apples are in a basket. 2 more apples are added.'];w=q.map((x,i)=>`<div class="story"><b>${i+1}. ${x}</b><span class="draw">DRAW THE MODEL</span></div>`).join('');break;}
case 19:{inst='Do NOT solve with an equation. Draw a picture that MODELS each separating story.';let q=['5 ducks are swimming. 2 swim away.','4 blocks are on a table. 1 is taken away.','5 cookies are on a plate. 3 are eaten.','3 toy cars are parked. 1 drives away.'];w=q.map((x,i)=>`<div class="story"><b>${i+1}. ${x}</b><span class="draw">DRAW THE MODEL</span></div>`).join('');break;}
case 20:inst='Term 1 check. Work independently.';w=`<div class="mixed"><b>1. Count:</b>${D(7,'sm')}${A()}</div><div class="mixed"><b>2. What comes after 18?</b>${A()}</div><div class="mixed"><b>3. Count by tens: 10, 20, 30,</b>${A()}</div><div class="mixed"><b>4. Circle the group with MORE:</b><span class="boxed">${D(4,'tiny')}</span><span class="boxed">${D(6,'tiny')}</span></div><div class="mixed"><b>5. One more than 8 is</b>${A()}</div><div class="mixed"><b>6. Name the shape:</b> △ ${A(80)}</div><div class="mixed"><b>7. Name the solid:</b> ⚽ ${A(80)}</div><div class="mixed"><b>8. Write a position word:</b> The star is ___ the box. ${A(80)}</div><div class="mixed"><b>9. Circle a measurable attribute:</b> ${C('length')} ${C('name')} ${C('happy')}</div><div class="story"><b>10. Draw a model: 2 bugs are on a leaf. 2 more join.</b><span class="draw">DRAW</span></div>`;break;
}return sh(n,t,s,inst,w)}
const sel=$('wsSelect'),grid=$('pickGrid'),pages=$('pages');meta.forEach((m,i)=>{sel.insertAdjacentHTML('beforeend',`<option value="${i+1}">Worksheet ${i+1}: ${m[0]}</option>`);grid.insertAdjacentHTML('beforeend',`<button type="button" class="pick" data-n="${i+1}"><strong>${i+1}. ${m[0]}</strong><span>${m[1]}</span></button>`)});
function show(n){pages.innerHTML=sheet(Number(n));sel.value=String(n);pages.scrollIntoView({behavior:'smooth',block:'start'})}grid.addEventListener('click',e=>{let b=e.target.closest('[data-n]');if(b)show(b.dataset.n)});sel.addEventListener('change',()=>show(sel.value));$('printOne').addEventListener('click',()=>window.print());$('printAll').addEventListener('click',()=>{pages.innerHTML=Array.from({length:20},(_,i)=>sheet(i+1)).join('');setTimeout(()=>window.print(),50)});window.addEventListener('afterprint',()=>show(sel.value));show(1);
})();