(()=>{'use strict';
const $=id=>document.getElementById(id),R=a=>a[Math.floor(Math.random()*a.length)],S=a=>[...a].sort(()=>Math.random()-.5),KEY='mila-literacy-v2';
const base={phonological:['Phonological Awareness',31,'Highest priority'],phonics:['Phonics & Word Recognition',31,'Highest priority'],vocabulary:['Vocabulary Acquisition & Use',38,'Priority'],print:['Print Concepts',44,'Developing'],informational:['Informational Text: Key Ideas & Details',56,'Maintain + build'],literature:['Literature: Key Ideas & Details',80,'Strength / maintain']};
const W=[['Hear the Sound Structure','Rhyme, syllables, first/last sounds'],['Letters Carry Sounds','Map speech sounds to printed letters'],['Blend to Read','Blend left-to-right and decode CVC words'],['Segment to Spell','Break words into sounds and map them to letters'],['Flexible Word Reading','Change one sound and read a new word'],['Build Automaticity','Read accurately with less effort'],['Words Build Knowledge','Grow vocabulary and informational language'],['Integrated Reading Mission','Combine decoding, meaning, and oral language']];
const D=['Sound Detective','Letter Mapper','Word Builder','Mastery Check'];
const pics=[['moon','🌙'],['sun','☀️'],['fish','🐟'],['dog','🐶'],['cat','🐱'],['ball','⚽'],['hat','🎩'],['pig','🐷'],['kite','🪁'],['leaf','🍃'],['rabbit','🐰'],['turtle','🐢'],['apple','🍎'],['car','🚗'],['van','🚐'],['goat','🐐'],['duck','🦆']];
const words=[['sat','🪑'],['mat','🧘'],['tap','🚰'],['pan','🍳'],['pin','📌'],['sit','🪑'],['tin','🥫'],['can','🥫'],['cap','🧢'],['cat','🐱'],['map','🗺️'],['dog','🐶'],['sun','☀️'],['hat','🎩'],['pig','🐷'],['fox','🦊'],['bus','🚌'],['bed','🛏️'],['cup','🥤'],['hen','🐔'],['bug','🐞'],['rat','🐀'],['bat','🦇'],['pen','🖊️'],['log','🪵'],['van','🚐']];
const voc=[['enormous','very, very big','an elephant','an ant','🐘','🐜'],['fragile','easy to break','a glass cup','a rock','🥛','🪨'],['observe','look closely and notice details','study a butterfly','close your eyes','🔎','🙈'],['predict','say what may happen next','use clues to guess the next event','repeat what already happened','🔮','↩️'],['habitat','the natural home of a plant or animal','a pond for a frog','a pencil box for a frog','🌿','✏️'],['compare','notice how things are alike and different','look at two leaves side by side','hide one leaf','⚖️','🙈'],['gather','bring things together','collect the blocks','scatter the blocks','🧺','💨'],['protect','keep something safe','use an umbrella in rain','leave a book in rain','☂️','🌧️']];
const info=[['Bees visit flowers. They carry pollen from flower to flower. This helps many plants make seeds.','What do bees help plants do?',['make seeds','turn into rocks','become cars'],0],['A turtle has a hard shell. The shell helps protect its body.','Why is a turtle shell useful?',['It protects the turtle','It makes music','It grows flowers'],0],['Rain fills puddles and gives plants water.','What is one thing rain does?',['gives plants water','turns leaves into metal','makes the sun colder'],0]];
const lit=[['Mia found a tiny seed. She planted it, watered it, and later saw a sprout.','What happened after Mia watered the seed?',['A sprout appeared','The seed became a shoe','She threw it away'],0],['Leo lost his red mitten. He looked under the chair and found it beside his backpack.','Where did Leo find the mitten?',['beside his backpack','inside the moon','underwater'],0]];
function blank(){let L={};for(let w=0;w<8;w++)for(let d=0;d<4;d++)L[`${w}-${d}`]={complete:false,best:0};let K={};Object.keys(base).forEach(k=>K[k]={c:0,a:0});return{lessons:L,skills:K,stars:0,c:0,a:0,streak:0,last:null}}
let p;try{p=Object.assign(blank(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{p=blank()}const save=()=>localStorage.setItem(KEY,JSON.stringify(p));
let st={w:0,d:0,r:0,c:0,a:0,stars:0,locked:false,prompt:'',hint:'',defer:null};
function view(v){['home','lesson','parent'].forEach(x=>$(`${x}View`).classList.toggle('active',x===v))}function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}
function resetStage(){st.locked=false;$('activityStage').innerHTML='';$('feedback').textContent='';$('feedback').className='feedback';$('hintBtn').classList.add('hidden');$('nextBtn').classList.add('hidden')}
function prompt(q,h,voice=q){$('promptText').textContent=q;st.prompt=voice;st.hint=h}
function choices(items,answer,skill){let g=document.createElement('div');g.className='choice-grid';S(items).forEach(x=>{let b=document.createElement('button');b.type='button';b.className='choice'+(String(x).length>12?' text':'');b.textContent=x;b.onclick=()=>score(x===answer,skill,b);g.appendChild(b)});$('activityStage').appendChild(g)}
function score(ok,skill,b){if(st.locked)return;st.a++;p.a++;p.skills[skill].a++;if(ok){st.c++;p.c++;p.skills[skill].c++;st.stars++;p.stars++;st.locked=true;b?.classList.add('correct');$('feedback').textContent='Correct — nice work.';$('feedback').className='feedback good';$('nextBtn').classList.remove('hidden');save()}else{b?.classList.add('wrong');$('feedback').textContent='Not yet. Try again.';$('feedback').className='feedback bad';$('hintBtn').classList.remove('hidden');save()}}
function practice(skill){p.skills[skill].a++;p.skills[skill].c++;st.stars++;p.stars++;st.locked=true;$('feedback').textContent='Done. Strong explanation.';$('feedback').className='feedback good';$('nextBtn').classList.remove('hidden');save()}
const first=w=>w[0].toLowerCase(),last=w=>w[w.length-1].toLowerCase();
const A={
first(){let t=R(pics),ans=first(t[0]),opts=S([t,...pics.filter(x=>first(x[0])!==ans)]).slice(0,3);if(!opts.includes(t))opts[0]=t;prompt(`Which picture starts with /${ans}/?`,'Say each word slowly and listen to the first sound.');let g=document.createElement('div');g.className='picture-grid';S(opts).forEach(x=>{let b=document.createElement('button');b.className='picture-choice';b.innerHTML=`<span class="emoji">${x[1]}</span><span class="label">${x[0]}</span>`;b.onclick=()=>score(first(x[0])===ans,'phonological',b);g.appendChild(b)});$('activityStage').appendChild(g)},
last(){let t=R(pics.filter(x=>x[0].length<7)),ans=last(t[0]),opts=[ans,...S('mnstpgkrlfd'.split('').filter(x=>x!==ans)).slice(0,2)];prompt(`What sound ends “${t[0]}”?`,'Stretch the last part of the word.');choices(opts,ans,'phonological')},
rhyme(){let sets=[['cat','hat','dog'],['sun','run','pig'],['map','cap','bed'],['fox','box','hen'],['hen','pen','bus']];let x=R(sets);prompt(`Which word rhymes with “${x[0]}”?`,'Rhyming words have the same ending sound.');choices([x[1],x[2]],x[1],'phonological')},
syll(){let t=R(pics),n=/rabbit|turtle|apple/.test(t[0])?2:1;prompt(`Clap the parts in “${t[0]}”. How many syllables?`,'Say it slowly and clap each beat.');choices([1,2,3],n,'phonological')},
blend(){let t=R(words),ss=t[0].split('');prompt(`Blend: /${ss.join('/ /')}/`,'Say each sound, then slide them together.',`Blend the sounds ${ss.join(', ')}.`);choices(S([t[0],...S(words.filter(x=>x[0]!==t[0])).slice(0,2).map(x=>x[0])]),t[0],'phonological')},
letter(){let t=R(pics),a=first(t[0]);prompt(`Which letter makes the first sound in “${t[0]}”?`,'Say the word and listen to the first sound.');choices([a,...S('abcdefghijklmnopqrstuvwxyz'.split('').filter(x=>x!==a)).slice(0,2)],a,'phonics')},
decode(){let t=R(words);prompt('Read the word. Then choose its picture.','Touch each letter, say each sound, then blend. Do not guess from the picture.',`Read the word ${t[0]}.`);let w=document.createElement('div');w.className='word-display';w.textContent=t[0];$('activityStage').appendChild(w);let opts=[t,...S(words.filter(x=>x[0]!==t[0])).slice(0,2)];let g=document.createElement('div');g.className='picture-grid';S(opts).forEach(x=>{let b=document.createElement('button');b.className='picture-choice';b.innerHTML=`<span class="emoji">${x[1]}</span>`;b.onclick=()=>score(x[0]===t[0],'phonics',b);g.appendChild(b)});$('activityStage').appendChild(g)},
missing(){let t=R(words),i=Math.floor(Math.random()*3),a=t[0][i],shown=t[0].split('');shown[i]='_';prompt(`Finish the word: ${shown.join('')}`,'Say the whole word, then listen for the missing sound.');choices([a,...S('abcdefghijklmnopqrstuvwxyz'.split('').filter(x=>x!==a)).slice(0,2)],a,'phonics')},
build(){let t=R(words),letters=S(t[0].split(''));prompt(`Build “${t[0]}” from its sounds.`,'Say the sounds from left to right.');let box=document.createElement('div');box.className='practice-card';box.innerHTML=`<div class="emoji">${t[1]}</div><div class="sound-row">${letters.map(x=>`<span class="sound-chip">${x}</span>`).join('')}</div><p class="muted">Point to the letters in the order you hear them, then say the word.</p>`;let b=document.createElement('button');b.className='btn primary';b.textContent='I built it';b.onclick=()=>practice('phonics');box.appendChild(b);$('activityStage').appendChild(box)},
print(){let qs=[['Where do we start reading a line?',['on the left','on the right','in the middle'],'on the left'],['What separates words in a sentence?',['spaces','numbers','pictures'],'spaces'],['Which direction do English words usually go?',['left to right','bottom to top','right to left'],'left to right']];let q=R(qs);prompt(q[0],'Think about how we track print on a page.');choices(q[1],q[2],'print')},
vocab(){let v=R(voc);prompt(`Which is an example of “${v[0]}”?`,'Use the meaning, not the picture alone.',`${v[0]} means ${v[1]}. Which is an example?`);let card=document.createElement('div');card.className='vocab-card';card.innerHTML=`<strong>${v[0]}</strong><span>${v[1]}</span>`;$('activityStage').appendChild(card);choices([`${v[4]} ${v[2]}`,`${v[5]} ${v[3]}`],`${v[4]} ${v[2]}`,'vocabulary')},
info(){let q=R(info);prompt(q[1],'Listen for the fact the text teaches.',`${q[0]} ${q[1]}`);let t=document.createElement('div');t.className='mini-text';t.textContent=q[0];$('activityStage').appendChild(t);choices(q[2],q[2][q[3]],'informational')},
lit(){let q=R(lit);prompt(q[1],'Use what actually happened in the story.',`${q[0]} ${q[1]}`);let t=document.createElement('div');t.className='mini-text';t.textContent=q[0];$('activityStage').appendChild(t);choices(q[2],q[2][q[3]],'literature')},
bridge(){prompt('Tell an adult one important thing you learned from today’s Wit & Wisdom text.','Add one detail or one new vocabulary word.');let c=document.createElement('div');c.className='practice-card';c.innerHTML='<div class="emoji">💬</div><h3>Knowledge connection</h3><p class="muted">This keeps strong comprehension active while decoding receives most of the intervention time.</p>';let b=document.createElement('button');b.className='btn primary';b.textContent='I explained it';b.onclick=()=>practice('literature');c.appendChild(b);$('activityStage').appendChild(c)}
};
function weak(){let rank=['phonological','phonics','vocabulary','print','informational','literature'],best=rank[0],gap=-1;rank.forEach(k=>{let s=p.skills[k],acc=s.a?s.c/s.a:0,priority=(100-base[k][1])/20,unc=s.a<5?1:0,g=priority+(1-acc)*3+unc;if(g>gap){gap=g;best=k}});return best}
function plan(){let w=st.w,core=w<1?['first','rhyme','syll','blend']:w<2?['letter','first','last','print']:w<3?['blend','letter','decode','missing']:w<4?['missing','build','decode','syll']:w<5?['decode','missing','build','letter']:w<6?['decode','decode','print','vocab']:w<7?['vocab','info','decode','bridge']:['decode','build','info','lit'];let k=weak(),adapt={phonological:'blend',phonics:'decode',vocabulary:'vocab',print:'print',informational:'info',literature:'lit'}[k];return [...core,adapt]}
function header(){let p1=plan();$('lessonEyebrow').textContent=`Week ${st.w+1} • Day ${st.d+1}`;$('lessonTitle').textContent=D[st.d];$('lessonGoal').textContent=W[st.w][1];$('lessonScore').textContent=`⭐ ${st.stars}`;$('roundLabel').textContent=`Round ${Math.min(st.r+1,p1.length)} of ${p1.length}${st.r===p1.length-1?' • Adaptive review':''}`;$('lessonBar').style.width=`${100*st.r/p1.length}%`}
function round(){resetStage();header();let q=plan();if(st.r>=q.length)return finish();A[q[st.r]]()}
function start(w,d){Object.assign(st,{w,d,r:0,c:0,a:0,stars:0});view('lesson');round()}
function finish(){let rec=p.lessons[`${st.w}-${st.d}`],pct=st.a?Math.round(100*st.c/st.a):0,was=rec.complete;rec.complete=true;rec.best=Math.max(rec.best||0,pct);if(!was){let today=new Date().toISOString().slice(0,10);if(p.last){let diff=(Date.parse(today)-Date.parse(p.last))/86400000;p.streak=diff===1?p.streak+1:diff===0?Math.max(1,p.streak):1}else p.streak=1;p.last=today}save();$('lessonBar').style.width='100%';$('roundLabel').textContent='Lesson complete';$('promptText').textContent='Literacy mission complete';let s=$('activityStage');s.innerHTML=`<div style="text-align:center"><div style="font-size:4rem">🏅</div><div class="prompt-big" style="margin:6px 0">${pct}% scored accuracy</div><p class="muted">Adaptive priority: <strong>${base[weak()][0]}</strong></p></div>`;let b=document.createElement('button');b.className='btn primary';b.textContent='Back to lessons';b.onclick=()=>{home();view('home')};s.appendChild(b);speak('Great work. You finished the literacy mission.')}
function home(){let g=$('weekGrid');g.innerHTML='';W.forEach((w,i)=>{let c=document.createElement('section');c.className='week-card card';let n=0;c.innerHTML=`<div class="eyebrow">Week ${i+1}</div><h3>${w[0]}</h3><p class="muted">${w[1]}</p>`;let l=document.createElement('div');l.className='lesson-list';D.forEach((d,j)=>{let r=p.lessons[`${i}-${j}`];if(r.complete)n++;let b=document.createElement('button');b.className='lesson-row'+(r.complete?' complete':'');b.innerHTML=`<span class="day">DAY ${j+1}</span><span class="name">${d}</span><span class="status">${r.complete?r.best+'% ✓':'Start'}</span>`;b.onclick=()=>start(i,j);l.appendChild(b)});c.appendChild(l);let f=document.createElement('div');f.className='week-progress';f.textContent=`${n}/4 lessons complete`;c.appendChild(f);g.appendChild(c)});let done=Object.values(p.lessons).filter(x=>x.complete).length;$('overallPct').textContent=Math.round(done/32*100)+'%';$('overallBar').style.width=(done/32*100)+'%'}
function parent(){let done=Object.values(p.lessons).filter(x=>x.complete).length;$('statLessons').textContent=`${done}/32`;$('statAccuracy').textContent=p.a?Math.round(100*p.c/p.a)+'%':'—';$('statStreak').textContent=p.streak;$('statStars').textContent=p.stars;let h='<table class="progress-table"><thead><tr><th>Domain</th><th>STAR</th><th>Plan role</th><th>In-app</th><th>Action</th></tr></thead><tbody>';Object.keys(base).forEach(k=>{let s=p.skills[k],a=s.a?Math.round(100*s.c/s.a):null,label=a===null?'Collect data':a>=90?'Secure / maintain':a>=80?'Advance + review':a>=70?'Repeat':'Reteach / increase review',cl=a!==null&&a>=90?'good':a!==null&&a>=70?'mid':'low';h+=`<tr><td><strong>${base[k][0]}</strong></td><td>${base[k][1]}</td><td>${base[k][2]}</td><td>${a===null?'—':a+'%'}</td><td><span class="badge ${cl}">${label}</span></td></tr>`});$('skillTableWrap').innerHTML=h+'</tbody></table>';let wh='<table class="progress-table"><thead><tr><th>Week</th><th>Completed</th><th>Best avg.</th></tr></thead><tbody>';W.forEach((w,i)=>{let rs=D.map((_,j)=>p.lessons[`${i}-${j}`]).filter(x=>x.complete),avg=rs.length?Math.round(rs.reduce((a,x)=>a+x.best,0)/rs.length):0;wh+=`<tr><td><strong>Week ${i+1}: ${w[0]}</strong></td><td>${rs.length}/4</td><td>${rs.length?avg+'%':'—'}</td></tr>`});$('parentTableWrap').innerHTML=wh+'</tbody></table>'}
$('backBtn').onclick=()=>{home();view('home')};$('parentBackBtn').onclick=()=>{home();view('home')};$('parentBtn').onclick=()=>{parent();view('parent')};$('nextBtn').onclick=()=>{st.r++;round()};$('speakBtn').onclick=()=>speak(st.prompt);$('hintBtn').onclick=()=>{$('feedback').textContent=st.hint;$('feedback').className='feedback hint'};$('resetBtn').onclick=()=>{if(confirm('Reset all Literacy Mission progress on this device?')){p=blank();save();parent();home()}};$('installBtn').onclick=async()=>{if(st.defer){st.defer.prompt();await st.defer.userChoice;st.defer=null}else $('installModal').classList.remove('hidden')};$('closeInstall').onclick=()=>$('installModal').classList.add('hidden');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();st.defer=e});home();view('home');if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('../sw.js').catch(()=>{});
})();
