(async()=>{
const {DOMAIN_META,DEFAULT_LETTERS,WORDS,SOUND_PICTURES,RHYMES,SYLLABLES,VOCAB,HEART_WORDS,STORIES,INFO,SENTENCES,WORD_CHAINS,WEEKS}=await import('./data.js');

const KEY='kg-literacy-mission-progress-v2',$=id=>document.getElementById(id),pick=a=>a[Math.floor(Math.random()*a.length)],uniq=a=>[...new Set(a)],shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const blank=()=>({version:2,lessons:{},stars:0,lastStudyDate:null,streak:0,domains:Object.fromEntries(Object.keys(DOMAIN_META).map(k=>[k,{correct:0,attempts:0}])),settings:{letters:'',topic:'',vocab:''}});
let progress;try{const p=JSON.parse(localStorage.getItem(KEY)||'null');progress=p?{...blank(),...p,domains:{...blank().domains,...(p.domains||{})},settings:{...blank().settings,...(p.settings||{})}}:blank()}catch{progress=blank()}
let st={week:0,day:0,round:0,correct:0,attempts:0,stars:0,locked:false,prompt:'',speak:'',hint:'',domain:'sound',timer:null,deferredInstall:null};
const save=()=>localStorage.setItem(KEY,JSON.stringify(progress)),lessonKey=(w,d)=>`${w}-${d}`,lesson=()=>WEEKS[st.week].days[st.day],activities=()=>lesson()[2],totalLessons=WEEKS.reduce((n,w)=>n+w.days.length,0);

function localDay(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dayDiff(a,b){const [ay,am,ad]=a.split('-').map(Number),[by,bm,bd]=b.split('-').map(Number);return Math.round((Date.UTC(by,bm-1,bd)-Date.UTC(ay,am-1,ad))/86400000)}
function streak(){const t=localDay();if(progress.lastStudyDate===t)return;progress.streak=progress.lastStudyDate&&dayDiff(progress.lastStudyDate,t)===1?(progress.streak||0)+1:1;progress.lastStudyDate=t}
function view(v){['home','lesson','parent'].forEach(x=>$(`${x}View`).classList.toggle('active',x===v));if(v==='home')home();if(v==='parent')parent();scrollTo({top:0,behavior:'smooth'})}
function taught(){const custom=uniq(((progress.settings.letters||'').toLowerCase().match(/[a-z]/g)||[]));return custom.length>=4?custom:uniq(DEFAULT_LETTERS[st.week].split(''))}
const allowed=(w,L)=>[...w].every(c=>L.includes(c));
function wordPool(){let p=WORDS.filter(x=>allowed(x.word,taught()));if(p.length<6){const f=uniq(DEFAULT_LETTERS[st.week].split(''));p=WORDS.filter(x=>allowed(x.word,f))}return p.length>=6?p:WORDS.slice(0,12)}
function clear(){if(st.timer){clearTimeout(st.timer);st.timer=null}$('activityStage').innerHTML='';$('feedback').textContent='';$('feedback').className='feedback';$('hintBtn').classList.add('hidden');$('nextBtn').classList.add('hidden');$('knowledgeBridge').classList.add('hidden');st.locked=false}
function head(prompt,domain,voice=prompt,hint=''){st.prompt=prompt;st.speak=voice;st.hint=hint;st.domain=domain;$('promptText').textContent=prompt;const m=DOMAIN_META[domain];$('skillPill').textContent=m.name;$('skillPill').className=`skill-pill ${m.css}`}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.88;u.pitch=1.02;speechSynthesis.speak(u)}
function record(ok,b){st.attempts++;const d=progress.domains[st.domain]||(progress.domains[st.domain]={correct:0,attempts:0});d.attempts++;if(ok){st.correct++;st.stars++;progress.stars=(progress.stars||0)+1;d.correct++;b?.classList.add('correct');$('feedback').textContent=pick(['Yes — you mapped it!','Correct. Nice sound work.','You got it!','Strong reading move.']);$('feedback').className='feedback good';st.locked=true;$('nextBtn').classList.remove('hidden');$('hintBtn').classList.add('hidden')}else{b?.classList.add('wrong');$('feedback').textContent='Not yet. Try again carefully.';$('feedback').className='feedback bad';$('hintBtn').classList.remove('hidden');if(b)st.timer=setTimeout(()=>b.classList.remove('wrong'),550)}save();lessonHeader()}
function choice(label,fn,cls=''){const b=document.createElement('button');b.type='button';b.className=`choice ${cls}`.trim();b.textContent=label;b.addEventListener('click',()=>fn(b));return b}
function textChoices(items,answer,cls='smalltext'){const g=document.createElement('div');g.className='choice-grid';shuffle(items).forEach(x=>g.appendChild(choice(x,b=>{if(!st.locked)record(x===answer,b)},cls)));$('activityStage').appendChild(g)}
function pictureChoices(items,answer){const g=document.createElement('div');g.className='choice-grid';shuffle(items).forEach(x=>{const b=choice(x.emoji,b=>{if(!st.locked)record(x.word===answer,b)},'emoji');b.setAttribute('aria-label',`picture of ${x.word}`);g.appendChild(b)});$('activityStage').appendChild(g)}
function picture(x,label=true){const d=document.createElement('div');d.className='picture-card';d.innerHTML=`<div><div class="emoji-big" aria-hidden="true">${x.emoji}</div>${label?`<div class="label">${x.word}</div>`:''}</div>`;return d}
const showHint=()=>{$('feedback').textContent=st.hint||'Say it slowly. Use the sounds, not the picture, to solve the printed word.';$('feedback').className='feedback hint'};

function rhyme(){const x=pick(RHYMES);head(`Which word rhymes with “${x.target}”?`,'sound',`Which word rhymes with ${x.target}?`,'Say the target and each choice aloud. Rhyming words have the same ending sound.');$('activityStage').appendChild(picture({word:x.target,emoji:x.emoji}));const g=document.createElement('div');g.className='choice-grid';shuffle(x.choices).forEach(([w,e])=>{const b=document.createElement('button');b.type='button';b.className='choice smalltext';b.innerHTML=`<div style="font-size:2.6rem">${e}</div><div>${w}</div>`;b.onclick=()=>{if(!st.locked)record(w===x.answer,b)};g.appendChild(b)});$('activityStage').appendChild(g)}
function syllable(){const x=pick(SYLLABLES);head(`How many syllables are in “${x.word}”?`,'sound',`Say ${x.word}. Clap the word parts. How many syllables?`,'Clap once for each beat you hear in the word.');$('activityStage').appendChild(picture(x));textChoices(['1','2','3','4'],String(x.count),'word')}
function soundItem(kind){const L=taught();let p=SOUND_PICTURES.filter(x=>kind==='first'?L.includes(x.first):(x.last.length===1&&L.includes(x.last)));if(p.length<4)p=SOUND_PICTURES.filter(x=>kind==='first'?x.first.length===1:x.last.length===1);return pick(p)}
function initialSound(){const x=soundItem('first'),others=shuffle(taught().filter(c=>c!==x.first)).slice(0,3);head(`What sound starts “${x.word}”?`,'sound',`Listen to ${x.word}. What sound do you hear first?`,'Stretch the beginning of the word. Then match that sound to its letter.');$('activityStage').appendChild(picture(x));textChoices(uniq([x.first,...others]).slice(0,4),x.first,'word')}
function finalSound(){const x=soundItem('last'),others=shuffle(taught().filter(c=>c!==x.last)).slice(0,3);head(`What sound ends “${x.word}”?`,'sound',`Listen to ${x.word}. What sound do you hear at the end?`,'Say the word slowly and hold onto the last sound.');$('activityStage').appendChild(picture(x));textChoices(uniq([x.last,...others]).slice(0,4),x.last,'word')}
function upperLower(){const l=pick(taught()),o=shuffle(taught().filter(x=>x!==l)).slice(0,3);head(`Find the lowercase partner for ${l.toUpperCase()}.`,'print',`Find the lowercase letter that matches uppercase ${l.toUpperCase()}.`,'Uppercase and lowercase can look different, but they name the same letter.');const p=document.createElement('div');p.className='letter-pair';p.innerHTML=`<div class="giant-letter">${l.toUpperCase()}</div><div class="equals">↔</div><div class="giant-letter" style="border-style:dashed">?</div>`;$('activityStage').appendChild(p);textChoices(uniq([l,...o]),l,'word')}
function letterSound(){let L=taught().filter(l=>SOUND_PICTURES.some(x=>x.first===l));if(L.length<3)L=['m','s','t','p','n','c'];const l=pick(L),target=pick(SOUND_PICTURES.filter(x=>x.first===l)),dist=shuffle(SOUND_PICTURES.filter(x=>x.first!==l)).slice(0,2);head(`Which picture begins with the sound for ${l}?`,'phonics',`Which picture starts with the sound made by the letter ${l}?`,'Say the letter sound, then name each picture slowly.');const d=document.createElement('div');d.className='prompt-big prompt-word';d.textContent=l;$('activityStage').appendChild(d);pictureChoices([target,...dist],target.word)}
function printConcept(){const k=pick(['word','letter','count','period','capital']);if(k==='word'){head('Which one is a whole word?','print',undefined,'A word is made of one or more letters and carries meaning.');textChoices(['cat','c','.'],'cat','word')}else if(k==='letter'){head('Which one is a single letter?','print',undefined,'A letter is one symbol used to build words.');textChoices(['m','map','?'],'m','word')}else if(k==='period'){head('Tap the period.','print',undefined,'A period looks like one small dot near the bottom of the line.');textChoices(['.','?','!'],'.','word')}else if(k==='capital'){head('Which sentence starts with a capital letter?','print',undefined,'The first word in a sentence begins with a capital letter.');textChoices(['The cat sat.','the cat sat.','the Cat sat.'],'The cat sat.','smalltext')}else{const x=pick([{s:'Sam sat.',n:2},{s:'I see a cat.',n:4},{s:'The dog can run.',n:4},{s:'A bug is red.',n:4}]);head('How many words are in this sentence?','print',`How many words are in: ${x.s}`,'Point to each group of letters separated by a space.');const d=document.createElement('div');d.className='sentence-card';d.textContent=x.s;$('activityStage').appendChild(d);textChoices(['2','3','4','5'],String(x.n),'word')}}
function distract(target,pool,n=2){let p=pool.filter(x=>x.word!==target.word&&x.word.length===target.word.length);if(p.length<n)p=WORDS.filter(x=>x.word!==target.word&&x.word.length===target.word.length);return shuffle(p).slice(0,n)}
function blend(){const p=wordPool(),t=pick(p),d=distract(t,p);head('Blend the sounds. Which word do they make?','phonics','Say each letter sound, then sweep the sounds together to make the word.','Do not use letter names. Say each sound, then blend without a long pause.');const r=document.createElement('div');r.className='sound-row';[...t.word].forEach((c,i)=>{const x=document.createElement('div');x.className='sound-chip';x.textContent=c;r.appendChild(x);if(i<t.word.length-1){const a=document.createElement('div');a.className='sound-arrow';a.textContent='→';r.appendChild(a)}});$('activityStage').appendChild(r);textChoices([t.word,...d.map(x=>x.word)],t.word,'word')}
function decode(){const p=wordPool(),t=pick(p),d=distract(t,p);head('Read the word. Tap the matching picture.','phonics','Read the printed word using its sounds, then choose the matching picture.','Sound out the letters from left to right. Do not guess from the pictures.');const w=document.createElement('div');w.className='prompt-big prompt-word';w.textContent=t.word;$('activityStage').appendChild(w);pictureChoices([t,...d],t.word)}
function build(domain='phonics'){const t=pick(wordPool()),letters=[...t.word],extras=shuffle(taught().filter(x=>!letters.includes(x))).slice(0,2),bank=shuffle([...letters,...extras]);head(`Build the word “${t.word}”.`,domain,`Build the word ${t.word}. Say it slowly and choose the letters for each sound in order.`,'Stretch the word. Listen for the first sound, middle vowel, and last sound.');$('activityStage').appendChild(picture(t,false));const slots=document.createElement('div');slots.className='word-build';letters.forEach(()=>{const s=document.createElement('div');s.className='word-slot';slots.appendChild(s)});$('activityStage').appendChild(slots);const wrap=document.createElement('div');wrap.className='letter-bank';const chosen=[];const reset=()=>{chosen.length=0;[...slots.children].forEach(x=>x.textContent='');[...wrap.children].forEach(x=>x.classList.remove('used'))};bank.forEach((l,i)=>{const b=document.createElement('button');b.type='button';b.className='letter-tile';b.textContent=l;b.onclick=()=>{if(st.locked||b.classList.contains('used')||chosen.length>=letters.length)return;chosen.push({l,i});b.classList.add('used');slots.children[chosen.length-1].textContent=l;if(chosen.length===letters.length){const made=chosen.map(x=>x.l).join('');if(made===t.word)record(true,b);else{record(false,b);st.timer=setTimeout(reset,750)}}};wrap.appendChild(b)});$('activityStage').appendChild(wrap);const c=document.createElement('button');c.type='button';c.className='btn secondary';c.textContent='Clear letters';c.style.marginTop='16px';c.onclick=reset;$('activityStage').appendChild(c)}
const segment=()=>build('sound');
function wordChain(){let p=WORD_CHAINS.filter(([a,b])=>allowed(a,taught())&&allowed(b,taught()));if(!p.length)p=WORD_CHAINS.slice(0,5);const [a,b]=pick(p);let i=0;while(i<a.length&&a[i]===b[i])i++;const ans=b[i],alts=shuffle(taught().filter(x=>x!==ans&&x!==a[i])).slice(0,3);head(`Change “${a}” to “${b}”. Which new letter do you need?`,'phonics',`Change ${a} to ${b}. Which sound and letter changes?`,'Say both words slowly. Find the sound that is different.');const box=document.createElement('div');box.className='sentence-card';box.innerHTML=`<span style="color:var(--muted)">${a}</span> &nbsp;→&nbsp; <strong>${b}</strong>`;$('activityStage').appendChild(box);textChoices(uniq([ans,...alts]).slice(0,4),ans,'word')}
function heartWord(){const t=pick(HEART_WORDS),o=shuffle(HEART_WORDS.filter(x=>x!==t)).slice(0,3);head(`Tap the word “${t}”.`,'phonics',`Find the word ${t}.`,'Look at every letter. These words should become automatic, but still pay attention to print.');textChoices([t,...o],t,'word')}
function vocab(){const x=pick(VOCAB);head(x.question,'vocabulary',`${x.word} means ${x.definition}. ${x.question}`,'Use the meaning of the word, not just what sounds familiar.');const w=document.createElement('div');w.className='vocab-word';w.textContent=x.word;$('activityStage').appendChild(w);const d=document.createElement('div');d.className='definition';d.textContent=x.definition;$('activityStage').appendChild(d);textChoices(x.choices,x.answer,'smalltext')}
function passage(x,domain,label,hint){head(x.question,domain,`${x.text} ${x.question}`,hint);const d=document.createElement('div');d.className='story-card';d.innerHTML=`<div class="mini-label">${label}</div>${x.text}`;$('activityStage').appendChild(d);textChoices(x.choices,x.answer,'smalltext')}
const sentenceMeaning=()=>{const x=pick(SENTENCES);head(x.question,'literature',`${x.text} ${x.question}`,'Read the sentence again. Answer only from what the words say.');const d=document.createElement('div');d.className='sentence-card';d.textContent=x.text;$('activityStage').appendChild(d);textChoices(x.choices,x.answer,'word')};
const meaningStory=()=>passage(pick(STORIES),'literature','Read-aloud / listening comprehension','Think about what happened first and what happened next.');
const meaningInfo=()=>passage(pick(INFO),'informational','Knowledge read-aloud','Listen for the key fact that directly answers the question.');

function accuracy(k){const d=progress.domains[k];return d&&d.attempts?Math.round(100*d.correct/d.attempts):null}
function adaptive(){const order=['sound','phonics','vocabulary','print','informational','literature'];const ranked=order.map((k,i)=>({k,a:accuracy(k),i})).sort((x,y)=>(x.a??(55+x.i*3))-(y.a??(55+y.i*3)));const k=ranked[0].k,p={sound:st.week<2?['rhyme','syllable','initialSound','finalSound']:['initialSound','finalSound','segment','rhyme'],phonics:st.week<2?['letterSound','upperLower']:st.week<4?['blend','decode','wordBuild','letterSound']:['decode','wordBuild','wordChain','heartWord'],vocabulary:['vocab'],print:['printConcept','upperLower'],informational:['meaningInfo'],literature:['meaningStory','sentenceMeaning']};return pick(p[k])}
const render={rhyme,syllable,initialSound,finalSound,upperLower,letterSound,printConcept,blend,decode,wordBuild:()=>build('phonics'),segment,wordChain,heartWord,vocab,sentenceMeaning,meaningStory,meaningInfo};
function round(){clear();let t=activities()[st.round];if(t==='adaptive')t=adaptive();$('roundLabel').textContent=`Round ${st.round+1} of ${activities().length}`;(render[t]||decode)();lessonHeader()}
function lessonHeader(){const l=lesson();$('lessonEyebrow').textContent=`Week ${st.week+1} • Day ${st.day+1}`;$('lessonTitle').textContent=l[0];$('lessonGoal').textContent=l[1];$('lessonScore').textContent=`⭐ ${st.stars}`;$('lessonBar').style.width=`${Math.round(100*st.round/activities().length)}%`}
function next(){st.round++;st.round>=activities().length?finish():round()}
const mastery=a=>a>=90?'Secure — advance':a>=80?'Advance + review':a>=70?'Repeat soon':'Reteach at easier level';
function finish(){clear();$('roundLabel').textContent='Lesson complete';$('promptText').textContent='Literacy Mission Complete';$('skillPill').textContent='Saved';$('skillPill').className='skill-pill phonics';$('lessonBar').style.width='100%';const a=st.attempts?Math.round(100*st.correct/st.attempts):0,k=lessonKey(st.week,st.day),old=progress.lessons[k],run={completed:true,correct:st.correct,attempts:st.attempts,accuracy:a,stars:st.stars,date:localDay()};progress.lessons[k]=!old||a>=(old.accuracy||0)?run:{...old,completed:true,lastRunAccuracy:a,date:localDay()};streak();save();$('activityStage').innerHTML=`<div style="text-align:center;max-width:620px"><div style="font-size:4rem">🏅</div><div class="prompt-big" style="font-size:2.3rem;margin:8px 0">You finished!</div><div style="font-size:1.35rem;font-weight:900">${st.correct} correct • ${st.attempts} attempts • ${a}%</div><p class="muted"><strong>${mastery(a)}</strong>. Accuracy matters more than speed.</p><div class="activity-actions"><button class="btn primary" id="finishBack">Back to lessons</button><button class="btn secondary" id="againBtn">Play again</button></div></div>`;$('finishBack').onclick=()=>view('home');$('againBtn').onclick=()=>start(st.week,st.day);bridge();speak('Great work. Literacy mission complete.')}
function bridgePrompts(){const topic=(progress.settings.topic||'today’s Wit and Wisdom text').trim(),v=(progress.settings.vocab||'').split(',').map(x=>x.trim()).filter(Boolean),word=v.length?pick(v):'one important word from class';return [`Tell one important thing you learned from ${topic}.`,`Retell something from ${topic}: what happened first, next, and last?`,`Use “${word}” in a sentence connected to ${topic}.`,`Explain “${word}” in your own words, then give an example and a non-example.`,`What detail from ${topic} helped you understand the main idea?`,`Ask one curious question you still have about ${topic}.`,`Compare two people, animals, objects, or ideas from ${topic}. How are they alike and different?`]}
function bridge(){$('knowledgeBridge').classList.remove('hidden');$('knowledgePrompt').textContent=pick(bridgePrompts())}
function start(w,d){Object.assign(st,{week:w,day:d,round:0,correct:0,attempts:0,stars:0,locked:false});view('lesson');round()}
function home(){const done=Object.values(progress.lessons).filter(x=>x?.completed).length,pct=Math.round(100*done/totalLessons);$('overallPct').textContent=`${pct}%`;$('overallBar').style.width=`${pct}%`;const g=$('weekGrid');g.innerHTML='';WEEKS.forEach((w,wi)=>{const c=document.createElement('section');c.className='week-card card';const n=w.days.filter((_,di)=>progress.lessons[lessonKey(wi,di)]?.completed).length;c.innerHTML=`<div class="eyebrow">Week ${wi+1}</div><h3>${w.title}</h3><p class="muted">${w.goal}</p>`;const list=document.createElement('div');list.className='lesson-list';w.days.forEach((d,di)=>{const r=progress.lessons[lessonKey(wi,di)],b=document.createElement('button');b.type='button';b.className=`lesson-row${r?.completed?' complete':''}`;b.innerHTML=`<span class="day">D${di+1}</span><span class="name">${d[0]}</span><span class="status">${r?.completed?`${r.accuracy}% ✓`:'Start'}</span>`;b.onclick=()=>start(wi,di);list.appendChild(b)});c.appendChild(list);const q=document.createElement('div');q.className='week-progress';q.textContent=`${n}/${w.days.length} complete`;c.appendChild(q);g.appendChild(c)})}
function totalAccuracy(){let c=0,a=0;Object.values(progress.domains).forEach(d=>{c+=d.correct||0;a+=d.attempts||0});return a?Math.round(100*c/a):null}
const badge=a=>a===null?'<span class="badge">Not measured</span>':a>=90?`<span class="badge good">${a}% secure</span>`:a>=80?`<span class="badge mid">${a}% review</span>`:`<span class="badge low">${a}% reteach</span>`;
function parent(){const done=Object.values(progress.lessons).filter(x=>x?.completed).length,a=totalAccuracy();$('statLessons').textContent=`${done}/${totalLessons}`;$('statAccuracy').textContent=a===null?'—':`${a}%`;$('statStreak').textContent=progress.streak||0;$('statStars').textContent=progress.stars||0;const dg=$('domainCards');dg.innerHTML='';Object.entries(DOMAIN_META).forEach(([k,m])=>{const x=accuracy(k),rec=x===null?m.baseline:x>=90?'Secure: maintain with mixed practice':x>=80?'Advance, but keep spaced review':x>=70?'Repeat this domain this week':'Reduce difficulty and reteach explicitly',c=document.createElement('div');c.className='domain-card';c.innerHTML=`<span>Instructional role: ${m.priority}</span><strong>${m.name}</strong><small>${x===null?'No app data yet':`${x}% in-app accuracy`} • ${rec}</small><div class="domain-bar"><i style="width:${x===null?0:clamp(x,0,100)}%"></i></div>`;dg.appendChild(c)});$('lettersInput').value=progress.settings.letters||'';$('topicInput').value=progress.settings.topic||'';$('vocabInput').value=progress.settings.vocab||'';const t=document.createElement('table');t.className='progress-table';t.innerHTML='<thead><tr><th>Week</th><th>Focus</th><th>Complete</th><th>Avg. accuracy</th><th>Decision</th></tr></thead>';const b=document.createElement('tbody');WEEKS.forEach((w,wi)=>{const r=w.days.map((_,di)=>progress.lessons[lessonKey(wi,di)]).filter(Boolean),done=r.filter(x=>x.completed).length,avg=r.length?Math.round(r.reduce((s,x)=>s+(x.accuracy||0),0)/r.length):null,tr=document.createElement('tr');tr.innerHTML=`<td>Week ${wi+1}</td><td>${w.title}</td><td>${done}/${w.days.length}</td><td>${avg===null?'—':`${avg}%`}</td><td>${badge(avg)}</td>`;b.appendChild(tr)});t.appendChild(b);$('parentTableWrap').innerHTML='';$('parentTableWrap').appendChild(t)}

$('backBtn').onclick=()=>view('home');$('parentBackBtn').onclick=()=>view('home');$('parentBtn').onclick=()=>view('parent');$('speakBtn').onclick=()=>speak(st.speak||st.prompt||'Literacy mission');$('hintBtn').onclick=showHint;$('nextBtn').onclick=next;$('newBridgeBtn').onclick=()=>{$('knowledgePrompt').textContent=pick(bridgePrompts())};
$('alignmentForm').onsubmit=e=>{e.preventDefault();progress.settings.letters=$('lettersInput').value.trim();progress.settings.topic=$('topicInput').value.trim();progress.settings.vocab=$('vocabInput').value.trim();save();$('settingsSaved').textContent='Saved on this device.';setTimeout(()=>{$('settingsSaved').textContent=''},2200)};
$('resetBtn').onclick=()=>{if(confirm('Reset all saved Literacy Mission progress and teacher-alignment settings on this device?')){progress=blank();save();parent();home()}};
$('installBtn').onclick=async()=>{if(st.deferredInstall){st.deferredInstall.prompt();await st.deferredInstall.userChoice;st.deferredInstall=null}else $('installModal').classList.remove('hidden')};$('closeInstall').onclick=()=>$('installModal').classList.add('hidden');$('installModal').onclick=e=>{if(e.target===$('installModal'))$('installModal').classList.add('hidden')};addEventListener('beforeinstallprompt',e=>{e.preventDefault();st.deferredInstall=e});
home();view('home');if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
