export const DOMAIN_META={
  sound:{name:'Phonological Awareness',priority:'Highest priority',css:'sound',baseline:'Current Term 1 focus: onset-rime, sound position, and sound manipulation.'},
  phonics:{name:'Phonics & Word Recognition',priority:'Highest priority',css:'phonics',baseline:'Current Term 1 focus: consonant sounds, short vowels, decoding, and phonetic spelling.'},
  vocabulary:{name:'Vocabulary Acquisition & Use',priority:'Support',css:'vocabulary',baseline:'Use class vocabulary and oral language to support reading.'},
  print:{name:'Print Concepts & Conventions',priority:'Current priority',css:'print',baseline:'Current Term 1 focus: directionality, spaces, capitals, punctuation, and letter formation.'},
  informational:{name:'Informational Text',priority:'Wit & Wisdom bridge',css:'informational',baseline:'Use current class texts for key details and knowledge.'},
  literature:{name:'Literature: Key Ideas & Details',priority:'Wit & Wisdom bridge',css:'literature',baseline:'Use current class texts for retell, characters, events, and evidence.'}
};

export const DEFAULT_LETTERS=['msatpincod','msatpincodgfrlhb','msatpincodgfrlhbuek','msatpincodgfrlhbuekvwjy','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz'];

export const WORDS=[
 ['map','🗺️'],['mat','🟫'],['sat','🪑'],['tap','🚰'],['pin','📌'],['pan','🍳'],['nap','😴'],['tin','🥫'],['cat','🐱'],['cap','🧢'],['can','🥫'],['dog','🐶'],['dot','⚫'],['pot','🍲'],['dig','⛏️'],['fog','🌫️'],['log','🪵'],['fan','🪭'],['fun','🎉'],['run','🏃'],['rat','🐀'],['ram','🐏'],['lip','👄'],['leg','🦵'],['rug','🧶'],['bug','🐛'],['bus','🚌'],['bun','🍞'],['hut','🛖'],['hat','🎩'],['hen','🐔'],['bed','🛏️'],['bat','🦇'],['bag','🎒'],['kid','🧒'],['van','🚐'],['web','🕸️'],['win','🏆'],['jam','🍓'],['jet','✈️'],['fox','🦊'],['box','📦']
].map(([word,emoji])=>({word,emoji}));

export const SOUND_PICTURES=[
 ['moon','🌙','m','n'],['sun','☀️','s','n'],['apple','🍎','a','l'],['tiger','🐯','t','r'],['pig','🐷','p','g'],['igloo','🧊','i','oo'],['nest','🪺','n','t'],['cat','🐱','c','t'],['octopus','🐙','o','s'],['dog','🐶','d','g'],['goat','🐐','g','t'],['fish','🐟','f','sh'],['rabbit','🐇','r','t'],['lion','🦁','l','n'],['hat','🎩','h','t'],['ball','⚽','b','l'],['kite','🪁','k','t'],['van','🚐','v','n'],['wagon','🛒','w','n'],['jet','✈️','j','t'],['yarn','🧶','y','n'],['zebra','🦓','z','a']
].map(([word,emoji,first,last])=>({word,emoji,first,last}));

export const RHYMES=[['cat','🐱','hat',[['hat','🎩'],['sun','☀️'],['pig','🐷']]],['dog','🐶','log',[['log','🪵'],['cat','🐱'],['sun','☀️']]],['sun','☀️','run',[['run','🏃'],['dog','🐶'],['hat','🎩']]],['pig','🐷','wig',[['wig','🧑‍🦰'],['map','🗺️'],['dog','🐶']]],['fox','🦊','box',[['box','📦'],['fan','🪭'],['cat','🐱']]]].map(([target,emoji,answer,choices])=>({target,emoji,answer,choices}));

export const SYLLABLES=[['sun','☀️',1],['cat','🐱',1],['apple','🍎',2],['rabbit','🐇',2],['tiger','🐯',2],['pencil','✏️',2],['banana','🍌',3],['elephant','🐘',3],['octopus','🐙',3],['dinosaur','🦕',3],['watermelon','🍉',4]].map(([word,emoji,count])=>({word,emoji,count}));

export const VOCAB=[
 ['enormous','very, very large','Which is enormous?','A whale',['A whale','A grape','A button']],['fragile','easy to break or damage','Which thing is fragile?','A glass cup',['A glass cup','A rubber ball','A pillow']],['observe','look or listen carefully to notice details','Which person is observing?','A child watching an ant closely',['A child watching an ant closely','A child sleeping','A child running away']],['compare','look at two things to notice how they are alike or different','Which action shows compare?','Looking at two leaves to see how they differ',['Looking at two leaves to see how they differ','Hiding both leaves','Throwing one leaf away']],['predict','say what you think will happen next using clues','Which is a prediction?','Those dark clouds may bring rain',['Those dark clouds may bring rain','The sky is blue right now','I found a rock']],['shelter','a place that protects people or animals','Which could be a shelter?','A sturdy tent in the rain',['A sturdy tent in the rain','A puddle','An open sidewalk']],['journey','a trip from one place to another','Which is a journey?','Traveling from home to another state',['Traveling from home to another state','Tying a shoe','Eating one cracker']],['curious','wanting to know or learn more','Who is curious?','A child asking how a cocoon changes',['A child asking how a cocoon changes','A child refusing to look','A child already asleep']],['rapid','very fast','Which is rapid?','A rabbit racing across a field',['A rabbit racing across a field','A snail crawling','A parked car']],['protect','keep something safe from harm','Which action protects?','Wearing a helmet on a bike',['Wearing a helmet on a bike','Leaving a bike in the road','Throwing the helmet away']],['habitat','the natural home of a plant or animal','Which is a frog habitat?','A wet pond edge',['A wet pond edge','A dry kitchen drawer','A parking space']],['ancient','from a very long time ago','Which could be ancient?','A tool made thousands of years ago',['A tool made thousands of years ago','A toy made today','A sandwich from lunch']]
].map(([word,definition,question,answer,choices])=>({word,definition,question,answer,choices}));

export const HEART_WORDS=['the','a','I','is','to','you','we','was'];
export const STORIES=[['Mia found a tiny seed. She put it in soil and gave it water. A few days later, a green sprout appeared.','What happened after Mia watered the seed?','A sprout appeared',['A sprout appeared','The seed became a rock','Mia lost her shoes']],['Leo heard thunder outside. He brought the dog inside before the rain began.','Why did Leo bring the dog inside?','A storm was coming',['A storm was coming','The dog wanted breakfast','It was bedtime']],['Nina built a tall block tower. Her little brother bumped the table, and the tower fell. Nina built it again with a wider base.','What did Nina do after the tower fell?','She rebuilt it with a wider base',['She rebuilt it with a wider base','She hid the blocks','She went to sleep']],['A turtle moved slowly across the path. Sam waited quietly until it reached the grass.','What does this show about Sam?','Sam was patient',['Sam was patient','Sam was asleep','Sam was racing the turtle']]].map(([text,question,answer,choices])=>({text,question,answer,choices}));
export const INFO=[['Owls have large eyes that help them see in dim light. Many owls hunt when it is dark.','Why are large eyes useful to many owls?','They help owls see in dim light',['They help owls see in dim light','They help owls swim','They make owls louder']],['A cactus stores water in its thick stem. This helps it survive in dry places where rain is rare.','What helps a cactus live in a dry place?','It stores water in its stem',['It stores water in its stem','It lives under the ocean','It eats rocks']],['Bees visit flowers to collect nectar and pollen. As they move between flowers, they can carry pollen from one flower to another.','What can bees carry between flowers?','Pollen',['Pollen','Sand','Snow']],['Penguins are birds, but they do not fly through the air. Their strong flippers help them move through water.','What helps penguins move through water?','Their flippers',['Their flippers','Their fur','Their horns']]].map(([text,question,answer,choices])=>({text,question,answer,choices}));
export const SENTENCES=[['The cat sat on a mat.','Who sat on the mat?','cat',['cat','dog','pig']],['A dog can run.','What can the dog do?','run',['run','nap','fly']],['The bug is on the rug.','Where is the bug?','rug',['rug','hat','bed']],['I can tap the pan.','What can I tap?','pan',['pan','dog','sun']],['The fox is in the box.','Where is the fox?','box',['box','web','van']]].map(([text,question,answer,choices])=>({text,question,answer,choices}));
export const WORD_CHAINS=[['map','mat'],['mat','sat'],['cat','cap'],['cap','map'],['pin','pan'],['dog','log'],['log','fog'],['hat','bat'],['bug','bun'],['bed','hen'],['fan','fun'],['rat','hat'],['van','fan'],['box','fox']];

export const WEEKS=[
 {title:'Print Direction & Letter Forms',goal:'Current Term 1: follow print left-to-right/top-to-bottom, notice spaces, connect spoken words to letter sequences, and form upper/lowercase letters.',days:[
  ['Track the Print','Follow words and recognize spaces between words.',['printConcept','printConcept','upperLower','printConcept','upperLower','letterSound']],['Upper + Lower Partners','Match uppercase and lowercase forms.',['upperLower','upperLower','upperLower','letterSound','printConcept','upperLower']],['Letters Carry Sounds','Connect a printed letter to its primary sound.',['letterSound','letterSound','initialSound','upperLower','letterSound','printConcept']],['Capital + Punctuation','Reinforce sentence starts and ending punctuation.',['printConcept','printConcept','upperLower','printConcept','sentenceMeaning','printConcept']],['Week 1 Check','Check print concepts and letter-form knowledge.',['adaptive','printConcept','upperLower','letterSound','printConcept','adaptive']]
 ]},
 {title:'Consonant Sound Map',goal:'Current Term 1: produce primary consonant sounds and connect sounds to letters.',days:[
  ['Beginning Sound Links','Hear the first sound and choose its letter.',['initialSound','initialSound','letterSound','initialSound','letterSound','upperLower']],['Fast Letter-Sound Match','Strengthen automatic consonant sound links.',['letterSound','letterSound','upperLower','letterSound','initialSound','letterSound']],['Sound + Letter Build','Use sound-to-letter mapping inside short words.',['wordBuild','initialSound','letterSound','wordBuild','decode','letterSound']],['Consonant Mix','Switch among letters, first sounds, and short words.',['letterSound','initialSound','decode','upperLower','wordBuild','letterSound']],['Week 2 Check','Check current consonant-sound mapping.',['adaptive','letterSound','initialSound','upperLower','decode','adaptive']]
 ]},
 {title:'Onset-Rime to Whole Words',goal:'Current Term 1: blend and segment one-syllable spoken words from beginning sound + word family into whole words.',days:[
  ['Blend to the Word','Push sounds together to make a CVC word.',['blend','blend','decode','blend','letterSound','decode']],['Stretch the Word','Pull a CVC word apart to hear its parts.',['segment','segment','wordBuild','segment','initialSound','decode']],['Read the Pattern','Decode short words rather than guessing from pictures.',['decode','blend','decode','wordBuild','decode','segment']],['Build the Pattern','Encode heard words using the sounds in order.',['wordBuild','segment','wordBuild','decode','wordBuild','blend']],['Week 3 Check','Check blending, segmenting, and CVC mapping.',['adaptive','blend','segment','decode','wordBuild','adaptive']]
 ]},
 {title:'First, Middle & Last Sounds',goal:'Current Term 1: isolate initial, medial, and final sounds in CVC words.',days:[
  ['First Sound','Identify and map the beginning sound.',['initialSound','initialSound','segment','letterSound','initialSound','decode']],['Last Sound','Listen all the way through for the final sound.',['finalSound','finalSound','segment','decode','finalSound','wordBuild']],['Middle Sound Through Stretching','Segment the full word and attend to the vowel in the middle.',['segment','wordBuild','segment','decode','segment','letterSound']],['Sound Position Mix','Move flexibly among first, middle, and final sounds.',['initialSound','finalSound','segment','wordBuild','decode','segment']],['Week 4 Check','Check sound positions in CVC words.',['adaptive','initialSound','finalSound','segment','decode','adaptive']]
 ]},
 {title:'Change One Sound',goal:'Current Term 1: add or substitute sounds to make new words and distinguish similar words by the sound that differs.',days:[
  ['Word Chains','Change one sound and make a new word.',['wordChain','wordChain','decode','wordChain','segment','wordChain']],['Hear the Difference','Compare similar CVC words and locate the changed sound.',['wordChain','decode','segment','wordChain','decode','wordChain']],['Say It, Change It, Read It','Manipulate a sound, then decode the new word.',['segment','wordChain','decode','wordChain','wordBuild','decode']],['Spell the Changed Word','Use sound analysis to encode the new word.',['wordChain','wordBuild','segment','wordBuild','decode','wordChain']],['Week 5 Check','Check phoneme manipulation and similar-word discrimination.',['adaptive','wordChain','segment','decode','wordBuild','adaptive']]
 ]},
 {title:'Short Vowels & Phonetic Spelling',goal:'Current Term 1: connect common short-vowel sounds to letters and spell simple words phonetically.',days:[
  ['Vowel Sound Inside the Word','Use segmentation to hear the middle vowel.',['segment','letterSound','segment','decode','wordBuild','letterSound']],['Blend Short-Vowel Words','Read CVC words by sound.',['blend','decode','blend','decode','segment','decode']],['Spell by Sound','Stretch the word and write/build one letter for each sound.',['wordBuild','segment','wordBuild','segment','wordBuild','decode']],['Read + Spell Mix','Move between decoding and encoding.',['decode','wordBuild','blend','segment','decode','wordBuild']],['Week 6 Check','Check short-vowel CVC reading and phonetic spelling.',['adaptive','segment','decode','wordBuild','letterSound','adaptive']]
 ]},
 {title:'Print Conventions + Writing Bridge',goal:'Current Term 1: letter formation, capitals, punctuation, and sound-based spelling support opinion writing on paper.',days:[
  ['Capital Starts','Recognize correct sentence capitalization.',['printConcept','upperLower','printConcept','sentenceMeaning','printConcept','decode']],['End Marks','Recognize and name ending punctuation.',['printConcept','printConcept','sentenceMeaning','printConcept','decode','printConcept']],['Write What You Hear','Use sound-to-letter mapping for simple words.',['wordBuild','segment','wordBuild','decode','wordBuild','printConcept']],['Opinion Prep','Read for meaning, then say an opinion with a reason before writing it by hand.',['sentenceMeaning','meaningStory','vocab','sentenceMeaning','printConcept','meaningStory']],['Week 7 Check','Check print conventions and spelling support.',['adaptive','printConcept','wordBuild','segment','sentenceMeaning','adaptive']]
 ]},
 {title:'Language + Class-Text Meaning',goal:'Current Term 1: use vocabulary/category knowledge while reinforcing key details, retell, characters, and informational facts from class reading.',days:[
  ['Word Meaning','Use oral vocabulary precisely.',['vocab','vocab','sentenceMeaning','vocab','meaningStory','vocab']],['Story Key Details','Answer from the story and explain what happened.',['meaningStory','meaningStory','sentenceMeaning','meaningStory','vocab','meaningStory']],['Informational Key Details','Answer from facts in a short informational text.',['meaningInfo','meaningInfo','vocab','meaningInfo','sentenceMeaning','meaningInfo']],['Print + Meaning Mix','Keep sound-to-print active while reading for meaning.',['decode','sentenceMeaning','printConcept','meaningStory','wordBuild','vocab']],['Week 8 Check','Check meaning without displacing foundational skill work.',['adaptive','meaningStory','meaningInfo','vocab','decode','adaptive']]
 ]},
 {title:'Term 1 Integration',goal:'Integrate print, sound positions, sound changes, decoding, spelling, and comprehension without front-loading later-term fluency targets.',days:[
  ['Sound-to-Print Circuit','Move from heard sound to letter to word.',['initialSound','finalSound','letterSound','segment','wordBuild','decode']],['Read + Spell Circuit','Decode, change, and encode CVC words.',['decode','wordChain','wordBuild','segment','decode','wordBuild']],['Print + Sentence Circuit','Use print conventions while reading short sentences.',['printConcept','sentenceMeaning','upperLower','decode','printConcept','sentenceMeaning']],['Meaning Circuit','Use story/information strengths to support precise language.',['meaningStory','meaningInfo','vocab','sentenceMeaning','meaningStory','vocab']],['Week 9 Check','Adaptive review of the current Term 1 system.',['adaptive','adaptive','decode','wordBuild','printConcept','adaptive']]
 ]},
 {title:'Term 1 Exit Check',goal:'Demonstrate the standards currently introduced before heavier later-term work on automatic sight words and broader fluency.',days:[
  ['Print & Letter Check','Directionality, spaces, letter forms, capitals, and punctuation.',['printConcept','upperLower','letterSound','printConcept','upperLower','printConcept']],['Sound Position Check','Beginning, middle-through-segmentation, and ending sounds.',['initialSound','finalSound','segment','initialSound','segment','finalSound']],['Sound Change + Word Check','Manipulate, decode, and spell short words.',['wordChain','decode','segment','wordBuild','wordChain','decode']],['Read + Understand','Connect accurate word reading to sentence and passage meaning.',['sentenceMeaning','meaningStory','decode','meaningInfo','vocab','sentenceMeaning']],['Final Term 1 Mastery','Balanced current-school check.',['printConcept','initialSound','segment','wordChain','decode','wordBuild']]
 ]}
];