(()=>{'use strict';
const M={sound:['Sound Awareness','Highest priority','sound'],phonics:['Phonics & Word Reading','Highest priority','phonics'],vocabulary:['Vocabulary','High priority','vocabulary'],print:['Print Concepts','Reinforce','print'],meaning:['Meaning & Comprehension','Strength / maintain','meaning']};
const T=[
['Hear It & See Print','Rhyme, syllables, first sounds, and how print works.'],['Sound Positions & Letter Links','Beginning/end sounds and automatic letter-sound connections.'],['Blend & Segment CVC Words','Move from individual sounds to whole words and back again.'],['Decode, Encode & Change Words','Read, spell, and manipulate one sound at a time.'],['Automaticity + Vocabulary','Reduce effort on known word patterns while growing oral language.'],['Sentences & Knowledge','Connect accurate word reading to meaning and knowledge.'],['Expand the Sound-Letter Map','Apply newly taught letters without losing blending routines.'],['Mixed Decoding & Informational Knowledge','Use foundational skills inside meaningful reading.'],['Automaticity & Oral Language','Make accurate decoding more efficient and language more precise.'],['Integration & Exit Check','Demonstrate the full path from speech sounds to print to meaning.']];
const N=['Sound Lab','Letter Lab','Word Lab','Meaning Lab','Mastery Check'];
const L=['msat','msatpin','msatpincod','msatpincodgfrl','msatpincodgfrlhbu','msatpincodgfrlhbuek','msatpincodgfrlhbuekvwjy','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz'];
const W=[['map','🗺️'],['mat','🟫'],['sat','🪑'],['tap','🚰'],['pin','📌'],['pan','🍳'],['nap','😴'],['tin','🥫'],['cat','🐱'],['cap','🧢'],['can','🥫'],['dog','🐶'],['dot','⚫'],['pot','🍲'],['dig','⛏️'],['fog','🌫️'],['log','🪵'],['fan','🪭'],['fun','🎉'],['run','🏃'],['rat','🐀'],['ram','🐏'],['lip','👄'],['leg','🦵'],['rug','🧶'],['bug','🐛'],['bus','🚌'],['bun','🍞'],['hut','🛖'],['hat','🎩'],['hen','🐔'],['bed','🛏️'],['bat','🦇'],['bag','🎒'],['kid','🧒'],['van','🚐'],['web','🕸️'],['win','🏆'],['jam','🍓'],['jet','✈️'],['fox','🦊'],['box','📦']];
const P=[['moon','🌙','m','n'],['sun','☀️','s','n'],['apple','🍎','a','l'],['tiger','🐯','t','r'],['pig','🐷','p','g'],['nest','🪺','n','t'],['cat','🐱','c','t'],['octopus','🐙','o','s'],['dog','🐶','d','g'],['goat','🐐','g','t'],['fish','🐟','f','h'],['rabbit','🐇','r','t'],['lion','🦁','l','n'],['hat','🎩','h','t'],['ball','⚽','b','l'],['kite','🪁','k','e'],['van','🚐','v','n'],['wagon','🛒','w','n'],['jet','✈️','j','t'],['yarn','🧶','y','n'],['zebra','🦓','z','a']];
const RH=[['cat','🐱','hat',['hat','sun','pig']],['dog','🐶','log',['log','cat','sun']],['sun','☀️','run',['run','dog','hat']],['fox','🦊','box',['box','fan','cat']],['fan','🪭','pan',['pan','pig','bed']]];
const SY=[['sun','☀️',1],['cat','🐱',1],['apple','🍎',2],['rabbit','🐇',2],['tiger','🐯',2],['pencil','✏️',2],['banana','🍌',3],['elephant','🐘',3],['octopus','🐙',3],['watermelon','🍉',4]];
const V=[['enormous','very, very large','A whale',['A whale','A grape','A button']],['fragile','easy to break or damage','A glass cup',['A glass cup','A rubber ball','A pillow']],['observe','look or listen carefully to notice details','Watching an ant closely',['Watching an ant closely','Sleeping','Running away']],['compare','notice how two things are alike or different','Looking at two leaves side by side',['Looking at two leaves side by side','Hiding both leaves','Throwing one away']],['predict','say what you think will happen next using clues','Dark clouds may bring rain',['Dark clouds may bring rain','The sky is blue now','I found a rock']],['shelter','a place that protects people or animals','A sturdy tent in rain',['A sturdy tent in rain','A puddle','An open sidewalk']],['curious','wanting to know or learn more','Asking how a cocoon changes',['Asking how a cocoon changes','Refusing to look','Falling asleep']],['protect','keep something safe from harm','Wearing a helmet on a bike',['Wearing a helmet on a bike','Leaving the bike in the road','Throwing the helmet away']]];
const S=[['The cat sat on a mat.','Who sat on the mat?','cat',['cat','dog','pig']],['A dog can run.','What can the dog do?','run',['run','nap','fly']],['The bug is on the rug.','Where is the bug?','rug',['rug','sun','bed']],['A hen is in the pen.','Who is in the pen?','hen',['hen','fox','cat']],['The kid has a red hat.','What does the kid have?','hat',['hat','log','cup']]];
const ST=[['Mia found a tiny seed. She put it in soil and gave it water. A few days later, a green sprout appeared.','What happened after Mia watered the seed?','A sprout appeared',['A sprout appeared','The seed became a rock','Mia lost her shoes']],['Leo heard thunder outside. He brought the dog inside before the rain began.','Why did Leo bring the dog inside?','A storm was coming',['A storm was coming','The dog wanted breakfast','It was bedtime']],['Nina built a tall block tower. Her brother bumped the table, and the tower fell. Nina built it again with a wider base.','What did Nina do after the tower fell?','She rebuilt it with a wider base',['She rebuilt it with a wider base','She hid the blocks','She went to sleep']]];
const IN=[['Owls have large eyes that help them see in dim light. Many owls hunt when it is dark.','Why are large eyes useful to many owls?','They help owls see in dim light',['They help owls see in dim light','They help owls swim','They make owls louder']],['A cactus stores water in its thick stem. This helps it survive where rain is rare.','What helps a cactus live in a dry place?','It stores water in its stem',['It stores water in its stem','It lives under the ocean','It eats rocks']],['Bees visit flowers to collect nectar and pollen. As they move, they can carry pollen between flowers.','What can bees carry between flowers?','Pollen',['Pollen','Sand','Snow']]];
const C=[['map','mat'],['cat','cap'],['pin','pan'],['dog','log'],['log','fog'],['hat','bat'],['bug','bun'],['fan','fun'],['van','fan'],['box','fox']],H=['the','a','I','is','to','you','we','was'];
const WP=[['rhyme','syll','first','print','letter'],['first','last','letter','upper','print'],['blend','segment','decode','build','letter'],['decode','build','chain','heart','segment'],['decode','chain','vocab','sentence','heart'],['heart','sentence','story','vocab','decode'],['letter','decode','build','last','segment'],['decode','chain','sentence','info','vocab'],['decode','heart','vocab','story','sentence'],['first','segment','decode','build','vocab']];
window.LIT_DATA={M,T,N,L,W,P,RH,SY,V,S,ST,IN,C,H,WP};
})();
