export const DOMAIN_META={
  sound:{name:'Phonological Awareness',priority:'Highest priority',css:'sound',baseline:'Daily sound work; this is a primary intervention target.'},
  phonics:{name:'Phonics & Word Recognition',priority:'Highest priority',css:'phonics',baseline:'Daily decoding and encoding; this is a primary intervention target.'},
  vocabulary:{name:'Vocabulary Acquisition & Use',priority:'High priority',css:'vocabulary',baseline:'Teach useful words with examples, non-examples, and oral use.'},
  print:{name:'Print Concepts',priority:'Reinforce',css:'print',baseline:'Reinforce directionality, words/spaces, capitals, and punctuation inside real reading.'},
  informational:{name:'Informational Text',priority:'Developing',css:'informational',baseline:'Build knowledge and evidence talk without displacing foundational skills.'},
  literature:{name:'Literature: Key Ideas & Details',priority:'Strength',css:'literature',baseline:'Maintain and use as leverage; do not over-drill.'}
};

export const DEFAULT_LETTERS=['msat','msatpin','msatpincod','msatpincodgfrl','msatpincodgfrlhbu','msatpincodgfrlhbuek','msatpincodgfrlhbuekvwjy','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz','abcdefghijklmnopqrstuvwxyz'];

export const WORDS=[
 ['map','🗺️'],['mat','🟫'],['sat','🪑'],['tap','🚰'],['pin','📌'],['pan','🍳'],['nap','😴'],['tin','🥫'],['cat','🐱'],['cap','🧢'],['can','🥫'],['dog','🐶'],['dot','⚫'],['pot','🍲'],['dig','⛏️'],['fog','🌫️'],['log','🪵'],['fan','🪭'],['fun','🎉'],['run','🏃'],['rat','🐀'],['ram','🐏'],['lip','👄'],['leg','🦵'],['rug','🧶'],['bug','🐛'],['bus','🚌'],['bun','🍞'],['hut','🛖'],['hat','🎩'],['hen','🐔'],['bed','🛏️'],['bat','🦇'],['bag','🎒'],['kid','🧒'],['van','🚐'],['web','🕸️'],['win','🏆'],['jam','🍓'],['jet','✈️'],['fox','🦊'],['box','📦']
].map(([word,emoji])=>({word,emoji}));

export const SOUND_PICTURES=[
 ['moon','🌙','m','n'],['sun','☀️','s','n'],['apple','🍎','a','l'],['tiger','🐯','t','r'],['pig','🐷','p','g'],['igloo','🧊','i','oo'],['nest','🪺','n','t'],['cat','🐱','c','t'],['octopus','🐙','o','s'],['dog','🐶','d','g'],['goat','🐐','g','t'],['fish','🐟','f','sh'],['rabbit','🐇','r','t'],['lion','🦁','l','n'],['hat','🎩','h','t'],['ball','⚽','b','l'],['kite','🪁','k','t'],['van','🚐','v','n'],['wagon','🛒','w','n'],['jet','✈️','j','t'],['yarn','🧶','y','n'],['zebra','🦓','z','a']
].map(([word,emoji,first,last])=>({word,emoji,first,last}));

export const RHYMES=[
 ['cat','🐱','hat',[['hat','🎩'],['sun','☀️'],['pig','🐷']]],['dog','🐶','log',[['log','🪵'],['cat','🐱'],['sun','☀️']]],['sun','☀️','run',[['run','🏃'],['dog','🐶'],['hat','🎩']]],['pig','🐷','wig',[['wig','🧑‍🦰'],['map','🗺️'],['dog','🐶']]],['fox','🦊','box',[['box','📦'],['fan','🪭'],['cat','🐱']]],['bed','🛏️','red',[['red','🔴'],['sun','☀️'],['log','🪵']]],['fan','🪭','pan',[['pan','🍳'],['pig','🐷'],['bed','🛏️']]]
].map(([target,emoji,answer,choices])=>({target,emoji,answer,choices}));

export const SYLLABLES=[['sun','☀️',1],['cat','🐱',1],['apple','🍎',2],['rabbit','🐇',2],['tiger','🐯',2],['pencil','✏️',2],['banana','🍌',3],['elephant','🐘',3],['octopus','🐙',3],['dinosaur','🦕',3],['watermelon','🍉',4]].map(([word,emoji,count])=>({word,emoji,count}));

export const VOCAB=[
 ['enormous','very, very large','Which is enormous?','A whale',['A whale','A grape','A button']],
 ['fragile','easy to break or damage','Which thing is fragile?','A glass cup',['A glass cup','A rubber ball','A pillow']],
 ['observe','look or listen carefully to notice details','Which person is observing?','A child watching an ant closely',['A child watching an ant closely','A child sleeping','A child running away']],
 ['compare','look at two things to notice how they are alike or different','Which action shows compare?','Looking at two leaves to see how they differ',['Looking at two leaves to see how they differ','Hiding both leaves','Throwing one leaf away']],
 ['predict','say what you think will happen next using clues','Which is a prediction?','Those dark clouds may bring rain',['Those dark clouds may bring rain','The sky is blue right now','I found a rock']],
 ['shelter','a place that protects people or animals','Which could be a shelter?','A sturdy tent in the rain',['A sturdy tent in the rain','A puddle','An open sidewalk']],
 ['journey','a trip from one place to another','Which is a journey?','Traveling from home to another state',['Traveling from home to another state','Tying a shoe','Eating one cracker']],
 ['curious','wanting to know or learn more','Who is curious?','A child asking how a cocoon changes',['A child asking how a cocoon changes','A child refusing to look','A child already asleep']],
 ['rapid','very fast','Which is rapid?','A rabbit racing across a field',['A rabbit racing across a field','A snail crawling','A parked car']],
 ['protect','keep something safe from harm','Which action protects?','Wearing a helmet on a bike',['Wearing a helmet on a bike','Leaving a bike in the road','Throwing the helmet away']],
 ['habitat','the natural home of a plant or animal','Which is a frog habitat?','A wet pond edge',['A wet pond edge','A dry kitchen drawer','A parking space']],
 ['ancient','from a very long time ago','Which could be ancient?','A tool made thousands of years ago',['A tool made thousands of years ago','A toy made today','A sandwich from lunch']]
].map(([word,definition,question,answer,choices])=>({word,definition,question,answer,choices}));

export const HEART_WORDS=['the','a','I','is','to','you','we','was'];
export const STORIES=[
 ['Mia found a tiny seed. She put it in soil and gave it water. A few days later, a green sprout appeared.','What happened after Mia watered the seed?','A sprout appeared',['A sprout appeared','The seed became a rock','Mia lost her shoes']],
 ['Leo heard thunder outside. He brought the dog inside before the rain began.','Why did Leo bring the dog inside?','A storm was coming',['A storm was coming','The dog wanted breakfast','It was bedtime']],
 ['Nina built a tall block tower. Her little brother bumped the table, and the tower fell. Nina built it again with a wider base.','What did Nina do after the tower fell?','She rebuilt it with a wider base',['She rebuilt it with a wider base','She hid the blocks','She went to sleep']],
 ['A turtle moved slowly across the path. Sam waited quietly until it reached the grass.','What does this show about Sam?','Sam was patient',['Sam was patient','Sam was asleep','Sam was racing the turtle']]
].map(([text,question,answer,choices])=>({text,question,answer,choices}));
export const INFO=[
 ['Owls have large eyes that help them see in dim light. Many owls hunt when it is dark.','Why are large eyes useful to many owls?','They help owls see in dim light',['They help owls see in dim light','They help owls swim','They make owls louder']],
 ['A cactus stores water in its thick stem. This helps it survive in dry places where rain is rare.','What helps a cactus live in a dry place?','It stores water in its stem',['It stores water in its stem','It lives under the ocean','It eats rocks']],
 ['Bees visit flowers to collect nectar and pollen. As they move between flowers, they can carry pollen from one flower to another.','What can bees carry between flowers?','Pollen',['Pollen','Sand','Snow']],
 ['Penguins are birds, but they do not fly through the air. Their strong flippers help them move through water.','What helps penguins move through water?','Their flippers',['Their flippers','Their fur','Their horns']]
].map(([text,question,answer,choices])=>({text,question,answer,choices}));
export const SENTENCES=[
 ['The cat sat on a mat.','Who sat on the mat?','cat',['cat','dog','pig']],['A dog can run.','What can the dog do?','run',['run','nap','fly']],['The bug is on the rug.','Where is the bug?','rug',['rug','hat','bed']],['I can tap the pan.','What can I tap?','pan',['pan','dog','sun']],['The fox is in the box.','Where is the fox?','box',['box','web','van']]
].map(([text,question,answer,choices])=>({text,question,answer,choices}));
export const WORD_CHAINS=[['map','mat'],['mat','sat'],['cat','cap'],['cap','map'],['pin','pan'],['dog','log'],['log','fog'],['hat','bat'],['bug','bun'],['bed','hen'],['fan','fun'],['rat','hat'],['van','fan'],['box','fox']];

export const WEEKS=[
 {title:'Hear It & See Print',goal:'Build rhyme, syllable awareness, first-sound attention, and basic print concepts.',days:[
  ['Rhyme Detective','Hear and match rhyming words',['rhyme','rhyme','syllable','printConcept','rhyme','vocab']],['Syllable Claps','Hear words as larger sound parts',['syllable','syllable','rhyme','printConcept','syllable','vocab']],['First Sound Finder','Notice the first sound in spoken words',['initialSound','initialSound','rhyme','syllable','initialSound','meaningStory']],['Letters Have Partners','Match uppercase/lowercase and connect print to sounds',['upperLower','upperLower','letterSound','printConcept','letterSound','vocab']],['Week 1 Mastery Check','Review the most important early-foundation skills',['adaptive','rhyme','syllable','initialSound','printConcept','adaptive']] ]},
 {title:'Sound Positions & Letter Links',goal:'Identify beginning/end sounds and strengthen automatic letter-sound connections.',days:[
  ['Beginning Sound Lab','Connect a spoken beginning sound to its letter',['initialSound','letterSound','initialSound','letterSound','upperLower','vocab']],['Ending Sound Lab','Listen all the way through a word for the final sound',['finalSound','finalSound','initialSound','finalSound','letterSound','meaningStory']],['Fast Letter-Sound Match','Make known letter-sound links more automatic',['letterSound','upperLower','letterSound','initialSound','letterSound','vocab']],['Sound Position Mix','Switch attention between beginning and ending sounds',['initialSound','finalSound','letterSound','finalSound','initialSound','printConcept']],['Week 2 Mastery Check','Check sound-position and letter-link accuracy',['adaptive','initialSound','finalSound','letterSound','upperLower','adaptive']] ]},
 {title:'Blend & Segment CVC Words',goal:'Move from individual sounds to whole words and from whole words back to sounds.',days:[
  ['Blend the Word','Blend three mapped sounds into a CVC word',['blend','blend','decode','blend','letterSound','vocab']],['Stretch & Build','Segment a spoken CVC word and build it with letters',['segment','segment','wordBuild','segment','initialSound','meaningStory']],['Read the Word','Decode unfamiliar CVC words instead of guessing',['decode','decode','blend','decode','wordBuild','vocab']],['Build the Word','Encode spoken words using sound-to-letter mapping',['wordBuild','wordBuild','segment','decode','wordBuild','printConcept']],['Week 3 Mastery Check','Check blending, segmenting, decoding, and encoding',['adaptive','blend','segment','decode','wordBuild','adaptive']] ]},
 {title:'Decode, Encode & Change Words',goal:'Strengthen CVC reading by manipulating one sound/letter at a time.',days:[
  ['CVC Decoder','Read CVC words and connect them to meaning',['decode','decode','decode','blend','wordBuild','vocab']],['CVC Speller','Hear, segment, and encode CVC words',['wordBuild','segment','wordBuild','segment','decode','meaningStory']],['Word Chains','Change one sound to make a new word',['wordChain','wordChain','decode','wordChain','segment','vocab']],['Heart Words 1','Build automatic recognition of a small set of high-frequency words',['heartWord','heartWord','decode','heartWord','sentenceMeaning','printConcept']],['Week 4 Mastery Check','Check CVC decoding/encoding and early automatic words',['adaptive','decode','wordBuild','wordChain','heartWord','adaptive']] ]},
 {title:'Automaticity + Vocabulary',goal:'Reduce effort on familiar word patterns while deliberately growing oral vocabulary.',days:[
  ['Fast CVC Reading','Recognize familiar CVC patterns with less sounding-out effort',['decode','decode','wordChain','decode','heartWord','vocab']],['Sound Switches','Manipulate one phoneme while preserving the rest of the word',['wordChain','segment','wordChain','blend','wordChain','vocab']],['Power Words','Learn useful academic vocabulary through examples and non-examples',['vocab','vocab','decode','vocab','meaningStory','vocab']],['Read for Meaning','Connect a decodable sentence to its meaning',['sentenceMeaning','decode','sentenceMeaning','heartWord','sentenceMeaning','vocab']],['Week 5 Mastery Check','Check automaticity without sacrificing accuracy',['adaptive','decode','wordChain','vocab','sentenceMeaning','adaptive']] ]},
 {title:'Sentences & Knowledge',goal:'Join accurate word reading with oral language and comprehension.',days:[
  ['Heart Words 2','Recognize common function words inside short reading',['heartWord','heartWord','sentenceMeaning','decode','heartWord','vocab']],['Sentence Reader','Read a short sentence and answer a meaning question',['sentenceMeaning','sentenceMeaning','decode','sentenceMeaning','heartWord','meaningStory']],['Story Thinker','Use strong listening comprehension to answer why/what-happened questions',['meaningStory','meaningStory','vocab','meaningStory','decode','vocab']],['Vocabulary in Context','Use new words to reason about examples and situations',['vocab','sentenceMeaning','vocab','meaningStory','vocab','decode']],['Week 6 Mastery Check','Check word reading while preserving meaning',['adaptive','heartWord','sentenceMeaning','vocab','meaningStory','adaptive']] ]},
 {title:'Expand the Sound-Letter Map',goal:'Add more consonants/vowels while preserving strong blending and segmenting routines.',days:[
  ['New Letter Links','Practice newer letter-sound correspondences',['letterSound','letterSound','initialSound','letterSound','decode','vocab']],['Decode New Patterns','Apply the expanded letter set to unfamiliar CVC words',['decode','blend','decode','wordBuild','decode','meaningInfo']],['Spell New Patterns','Segment and encode with the expanded letter set',['wordBuild','segment','wordBuild','finalSound','wordBuild','vocab']],['Beginning to End','Track the first, middle, and final parts of short words',['initialSound','finalSound','segment','blend','wordChain','printConcept']],['Week 7 Mastery Check','Check transfer to newly learned letters and words',['adaptive','letterSound','decode','wordBuild','segment','adaptive']] ]},
 {title:'Mixed Decoding & Informational Knowledge',goal:'Apply foundational reading while building knowledge from informational language.',days:[
  ['Mixed Word Reading','Decode across the full taught letter set',['decode','heartWord','decode','wordChain','decode','vocab']],['Word Change Challenge','Manipulate sounds quickly and accurately',['wordChain','wordChain','segment','blend','wordChain','vocab']],['Sentence + Evidence','Read and answer from the words actually on the page',['sentenceMeaning','sentenceMeaning','decode','sentenceMeaning','heartWord','vocab']],['Information Detective','Listen for key facts and explain what was learned',['meaningInfo','meaningInfo','vocab','meaningInfo','decode','vocab']],['Week 8 Mastery Check','Check foundational skills inside meaningful reading',['adaptive','decode','wordChain','sentenceMeaning','meaningInfo','adaptive']] ]},
 {title:'Automaticity & Oral Language',goal:'Make accurate decoding more efficient while expanding precise spoken language.',days:[
  ['Accuracy Before Speed','Read known patterns smoothly without guessing',['decode','decode','heartWord','decode','sentenceMeaning','vocab']],['Word Memory','Strengthen orthographic mapping through reading, changing, and spelling',['wordChain','wordBuild','decode','segment','heartWord','vocab']],['Vocabulary Builder','Explain and apply increasingly useful words',['vocab','vocab','meaningInfo','vocab','meaningStory','vocab']],['Strong Comprehender','Use story strength to support retell, inference, and explanation',['meaningStory','meaningInfo','sentenceMeaning','meaningStory','vocab','decode']],['Week 9 Adaptive Check','Spend extra rounds on whichever domain currently needs it most',['adaptive','adaptive','decode','adaptive','vocab','adaptive']] ]},
 {title:'Integration & Exit Check',goal:'Demonstrate the complete path from speech sounds to print to meaning.',days:[
  ['Sound-to-Print Review','Review phoneme awareness and letter-sound mapping',['initialSound','finalSound','segment','letterSound','blend','vocab']],['Read + Spell Review','Decode and encode CVC words independently',['decode','wordBuild','wordChain','decode','segment','heartWord']],['Read + Understand','Connect word recognition to sentence and passage meaning',['sentenceMeaning','meaningStory','decode','meaningInfo','vocab','sentenceMeaning']],['Priority Repair','Target the weakest measured domains before the final check',['adaptive','adaptive','adaptive','adaptive','adaptive','adaptive']],['Final Mastery Check','Complete a balanced exit check across the literacy system',['rhyme','segment','decode','wordBuild','vocab','meaningStory']] ]}
];
