(()=>{'use strict';
const $=id=>document.getElementById(id),pick=a=>a[Math.floor(Math.random()*a.length)],shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},uniq=a=>[...new Set(a)],KEY='mila-literacy-v3';
const {M,T,N,L,W,P,RH,SY,V,S,ST,IN,C,H,WP}=window.LIT_DATA;
function blank(){let d={};Object.keys(M).forEach(k=>d[k]={c:0,a:0});return{lessons:{},domains:d,stars:0,streak:0,last:null,settings:{letters:'',topic:'',vocab:''}}}
let p;try{p=Object.assign(blank(),JSON.parse(localStorage.getItem(KEY)||'{}'));p.domains=Object.assign(blank().domains,p.domains||{});p.settings=Object.assign(blank().settings,p.settings||{})}catch{p=blank()}const save=()=>localStorage.setItem(KEY,JSON.stringify(p));
let st={w:0,d:0,r:0,c:0,a:0,stars:0,locked:false,domain:'sound',prompt:'',hint:'',defer:null};
function view(v){['home','lesson','parent'].forEach(x=>$(`${x}View`).classList.toggle('active',x===v));if(v==='home')home();if(v==='parent')parent();scrollTo({top:0,behavior:'smooth'})}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.9;speechSynthesis.speak(u)}
function letters(){let c=uniq((p.settings.letters.toLowerCase().match(/[a-z]/g)||[]));return c.length>=4?c:uniq(L[st.w].split(''))}
function pool(){let a=letters(),q=W.filter(x=>[...x[0]].every(c=>a.includes(c)));return q.length>=5?q:W.filter(x=>[...x[0]].every(c=>L[st.w].includes(c))).slice(0,18)}
function clear(){st.locked=false;$('activityStage').innerHTML='';$('feedback').textContent='';$('feedback').className='feedback';$('hintBtn').classList.add('hidden');$('nextBtn').classList.add('hidden');$('knowledgeBridge').classList.add('hidden')}
function head(q,d,h,voice=q){st.domain=d;st.prompt=voice;st.hint=h;$('promptText').textContent=q;let m=M[d];$('skillPill').textContent=m[0];$('skillPill').className=`skill-pill ${m[2]}`}
function choices(a,ans,cls='smalltext'){let g=document.createElement('div');g.className='choice-grid';shuffle(a).forEach(x=>{let b=document.createElement('button');b.type='button';b.className=`choice ${cls}`;b.textContent=x;b.onclick=()=>score(x===ans,b);g.appendChild(b)});$('activityStage').appendChild(g)}
function score(ok,b){if(st.locked)return;st.a++;let d=p.domains[st.domain];d.a++;if(ok){st.c++;st.stars++;p.stars++;d.c++;st.locked=true;b?.classList.add('correct');$('feedback').textContent=pick(['Correct — nice work.','Yes. Strong reading move.','You got it.']);$('feedback').className='feedback good';$('nextBtn').classList.remove('hidden');$('hintBtn').classList.add('hidden')}else{b?.classList.add('wrong');$('feedback').textContent='Not yet. Try again carefully.';$('feedback').className='feedback bad';$('hintBtn').classList.remove('hidden');setTimeout(()=>b?.classList.remove('wrong'),500)}save();hdr()}
function pic(x,label=true){let d=document.createElement('div');d.className='picture-card';d.innerHTML=`<div><div class="emoji-big">${x[1]}</div>${label?`<div class="label">${x[0]}</div>`:''}</div>`;return d}
function pictureChoices(items,ans){let g=document.createElement('div');g.className='choice-grid';shuffle(items).forEach(x=>{let b=document.createElement('button');b.type='button';b.className='choice emoji';b.textContent=x[1];b.title=x[0];b.setAttribute('aria-label',`picture of ${x[0]}`);b.onclick=()=>score(x[0]===ans,b);g.appendChild(b)});$('activityStage').appendChild(g)}
const A={
rhyme(){let x=pick(RH);head(`Which word rhymes with “${x[0]}”?`,'sound','Say each choice aloud. Rhyming words share the ending sound.');$('activityStage').appendChild(pic(x));choices(x[3],x[2],'word')},
syll(){let x=pick(SY);head(`How many syllables are in “${x[0]}”?`,'sound','Clap once for each beat in the word.',`Say ${x[0]}. Clap the word parts. How many syllables?`);$('activityStage').appendChild(pic(x));choices(['1','2','3','4'],String(x[2]),'word')},
first(){let q=P.filter(x=>letters().includes(x[2])),x=pick(q.length?q:P),ans=x[2],o=uniq([ans,...shuffle(letters().filter(z=>z!==ans)).slice(0,3)]);head(`What sound starts “${x[0]}”?`,'sound','Stretch the beginning of the word and match that sound to its letter.',`Listen to ${x[0]}. What sound do you hear first?`);$('activityStage').appendChild(pic(x));choices(o,ans,'word')},
last(){let q=P.filter(x=>x[3].length===1),x=pick(q),ans=x[3],o=uniq([ans,...shuffle(letters().filter(z=>z!==ans)).slice(0,3)]);head(`What sound ends “${x[0]}”?`,'sound','Say the word slowly and hold onto the last sound.',`Listen to ${x[0]}. What sound do you hear at the end?`);$('activityStage').appendChild(pic(x));choices(o,ans,'word')},
upper(){let x=pick(letters()),o=uniq([x,...shuffle(letters().filter(z=>z!==x)).slice(0,3)]);head(`Find the lowercase partner for ${x.toUpperCase()}.`,'print','Uppercase and lowercase can look different but name the same letter.');let d=document.createElement('div');d.className='prompt-big';d.textContent=x.toUpperCase();$('activityStage').appendChild(d);choices(o,x,'word')},
letter(){let q=P.filter(x=>letters().includes(x[2])),x=pick(q.length?q:P),d=shuffle(P.filter(z=>z[2]!==x[2])).slice(0,2);head(`Which picture begins with the sound for ${x[2]}?`,'phonics','Say the letter sound, then name each picture slowly.');let big=document.createElement('div');big.className='prompt-big';big.textContent=x[2];$('activityStage').appendChild(big);pictureChoices([x,...d],x[0])},
print(){let q=pick([['Which one is a whole word?',['cat','c','.'],'cat'],['Which one is a single letter?',['m','map','?'],'m'],['Tap the period.',['.','?','!'],'.'],['Which sentence starts with a capital letter?',['The cat sat.','the cat sat.','the Cat sat.'],'The cat sat.']]);head(q[0],'print','Look at how letters, words, spaces, and punctuation work on a page.');choices(q[1],q[2],'smalltext')},
blend(){let q=pool(),x=pick(q),ds=shuffle(q.filter(z=>z[0]!==x[0])).slice(0,2);head('Blend the sounds. Which word do they make?','phonics','Say each sound, then sweep them together without a long pause.');let r=document.createElement('div');r.className='sound-row';[...x[0]].forEach(c=>{let s=document.createElement('div');s.className='sound-chip';s.textContent=c;r.appendChild(s)});$('activityStage').appendChild(r);choices([x[0],...ds.map(z=>z[0])],x[0],'word')},
decode(){let q=pool(),x=pick(q),ds=shuffle(q.filter(z=>z[0]!==x[0])).slice(0,2);head('Read the word. Tap the matching picture.','phonics','Sound out the letters from left to right. Do not guess from the pictures.');let w=document.createElement('div');w.className='prompt-big';w.textContent=x[0];$('activityStage').appendChild(w);pictureChoices([x,...ds],x[0])},
build(){build('phonics')},segment(){build('sound')},
chain(){let q=C.filter(([a,b])=>[...a+b].every(c=>letters().includes(c)));let [a,b]=pick(q.length?q:C.slice(0,4)),i=[...a].findIndex((c,j)=>c!==b[j]),ans=b[i];head(`Change “${a}” to “${b}”. Which new letter do you need?`,'phonics','Say both words slowly and listen for the sound that changes.');let d=document.createElement('div');d.className='sentence-card';d.textContent=`${a} → ${b}`;$('activityStage').appendChild(d);choices(uniq([ans,...shuffle(letters().filter(z=>z!==ans)).slice(0,3)]),ans,'word')},
heart(){let x=pick(H);head(`Tap the word “${x}”.`,'phonics','Look at every letter. High-frequency words should become automatic, not guessed.');choices([x,...shuffle(H.filter(z=>z!==x)).slice(0,3)],x,'word')},
vocab(){let x=pick(V);head(`Which is an example of “${x[0]}”?`,'vocabulary','Use the meaning, not what merely sounds familiar.',`${x[0]} means ${x[1]}. Which is an example?`);let d=document.createElement('div');d.className='vocab-card';d.innerHTML=`<strong>${x[0]}</strong><span>${x[1]}</span>`;$('activityStage').appendChild(d);choices(x[3],x[2],'smalltext')},
sentence(){let x=pick(S);head(x[1],'meaning','Read the sentence again and answer only from what the words say.',`${x[0]} ${x[1]}`);let d=document.createElement('div');d.className='sentence-card';d.textContent=x[0];$('activityStage').appendChild(d);choices(x[3],x[2],'word')},
story(){passage(ST,'Story read-aloud')},info(){passage(IN,'Knowledge read-aloud')}
};
function build(domain){let q=pool(),x=pick(q),a=[...x[0]],bank=shuffle([...a,...shuffle(letters().filter(c=>!a.includes(c))).slice(0,2)]),made=[];head(`Build the word “${x[0]}”.`,domain,'Stretch the word. Listen for first sound, middle vowel, and last sound.',`Build the word ${x[0]}. Say it slowly and choose the letters in order.`);$('activityStage').appendChild(pic(x,false));let slots=document.createElement('div');slots.className='word-build';a.forEach(()=>{let s=document.createElement('div');s.className='word-slot';slots.appendChild(s)});$('activityStage').appendChild(slots);let wrap=document.createElement('div');wrap.className='letter-bank';bank.forEach((c,i)=>{let b=document.createElement('button');b.type='button';b.className='letter-tile';b.textContent=c;b.onclick=()=>{if(st.locked||b.classList.contains('used')||made.length===3)return;made.push([c,b]);b.classList.add('used');slots.children[made.length-1].textContent=c;if(made.length===3){let ok=made.map(z=>z[0]).join('')===x[0];score(ok,b);if(!ok)setTimeout(()=>{made.forEach(z=>z[1].classList.remove('used'));made=[];[...slots.children].forEach(s=>s.textContent='')},650)}};wrap.appendChild(b)});$('activityStage').appendChild(wrap)}
function passage(src,label){let x=pick(src);head(x[1],'meaning','Listen for the detail that directly answers the question.',`${x[0]} ${x[1]}`);let d=document.createElement('div');d.className='mini-text';d.innerHTML=`<div class="mini-label">${label}</div>${x[0]}`;$('activityStage').appendChild(d);choices(x[3],x[2],'smalltext')}
function acc(k){let d=p.domains[k];return d.a?Math.round(100*d.c/d.a):null}
function adaptive(){let order=['sound','phonics','vocabulary','print','meaning'],k=order.sort((a,b)=>(acc(a)??(a==='sound'||a==='phonics'?45:60))-(acc(b)??(b==='sound'||b==='phonics'?45:60)))[0],q={sound:['rhyme','first','last','segment'],phonics:['letter','blend','decode','build','chain','heart'],vocabulary:['vocab'],print:['print','upper'],meaning:['sentence','story','info']}[k];return pick(q)}
function plan(){let q=WP[st.w],a=[q[st.d%q.length],q[(st.d+1)%q.length],q[(st.d+2)%q.length],q[(st.d+3)%q.length],st.d===4?'adaptive':q[(st.d+4)%q.length],'adaptive'];return a}
function hdr(){let q=plan();$('lessonEyebrow').textContent=`Week ${st.w+1} • Day ${st.d+1}`;$('lessonTitle').textContent=N[st.d];$('lessonGoal').textContent=T[st.w][1];$('lessonScore').textContent=`⭐ ${st.stars}`;$('roundLabel').textContent=`Round ${Math.min(st.r+1,q.length)} of ${q.length}`;$('lessonBar').style.width=`${Math.round(100*st.r/q.length)}%`}
function round(){clear();hdr();let q=plan(),t=q[st.r];if(t==='adaptive')t=adaptive();A[t]();}
function start(w,d){Object.assign(st,{w,d,r:0,c:0,a:0,stars:0,locked:false});view('lesson');round()}
function next(){st.r++;if(st.r>=plan().length)return finish();round()}
function date(){let x=new Date();return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function finish(){clear();let a=st.a?Math.round(100*st.c/st.a):0,k=`${st.w}-${st.d}`,old=p.lessons[k];if(!old||a>=(old.acc||0))p.lessons[k]={done:true,acc:a,date:date()};else old.done=true;let today=date();if(p.last!==today){if(p.last){let z=(Date.parse(today)-Date.parse(p.last))/86400000;p.streak=z===1?(p.streak||0)+1:1}else p.streak=1;p.last=today}save();$('lessonBar').style.width='100%';$('roundLabel').textContent='Lesson complete';$('promptText').textContent='Literacy mission complete';$('skillPill').textContent='Saved';let d=$('activityStage');d.innerHTML=`<div style="text-align:center"><div style="font-size:4rem">🏅</div><div class="prompt-big" style="font-size:2rem">${a}% accuracy</div><p class="muted">${a>=90?'Secure — advance.':a>=80?'Advance with review.':a>=70?'Repeat soon.':'Reduce difficulty and reteach.'}</p><button class="btn primary" id="doneBtn">Back to lessons</button></div>`;$('doneBtn').onclick=()=>view('home');bridge();speak('Great work. Literacy mission complete.')}
function bridge(){let topic=p.settings.topic||'today’s Wit and Wisdom text',vs=p.settings.vocab.split(',').map(x=>x.trim()).filter(Boolean),v=vs.length?pick(vs):'one important class word',q=pick([`Tell one important thing you learned from ${topic}.`,`Retell something from ${topic}: first, next, last.`,`Use “${v}” in a sentence about ${topic}.`,`Explain “${v}” and give an example and a non-example.`,`What detail from ${topic} helped you understand the main idea?`]);$('knowledgePrompt').textContent=q;$('knowledgeBridge').classList.remove('hidden')}
function home(){let done=Object.values(p.lessons).filter(x=>x.done).length;$('overallPct').textContent=`${Math.round(done/50*100)}%`;$('overallBar').style.width=`${Math.round(done/50*100)}%`;let g=$('weekGrid');g.innerHTML='';T.forEach((t,w)=>{let c=document.createElement('section');c.className='week-card card';let n=0;c.innerHTML=`<div class="eyebrow">Week ${w+1}</div><h3>${t[0]}</h3><p class="muted">${t[1]}</p>`;let l=document.createElement('div');l.className='lesson-list';N.forEach((name,d)=>{let r=p.lessons[`${w}-${d}`];if(r?.done)n++;let b=document.createElement('button');b.type='button';b.className=`lesson-row${r?.done?' complete':''}`;b.innerHTML=`<span class="day">D${d+1}</span><span class="name">${name}</span><span class="status">${r?.done?r.acc+'% ✓':'Start'}</span>`;b.onclick=()=>start(w,d);l.appendChild(b)});c.appendChild(l);let x=document.createElement('div');x.className='week-progress';x.textContent=`${n}/5 complete`;c.appendChild(x);g.appendChild(c)})}
function badge(a){return a==null?'<span class="badge">Not measured</span>':a>=90?`<span class="badge good">${a}% secure</span>`:a>=80?`<span class="badge mid">${a}% review</span>`:`<span class="badge low">${a}% reteach</span>`}
function parent(){let done=Object.values(p.lessons).filter(x=>x.done).length,c=0,a=0;Object.values(p.domains).forEach(d=>{c+=d.c;a+=d.a});$('statLessons').textContent=`${done}/50`;$('statAccuracy').textContent=a?`${Math.round(100*c/a)}%`:'—';$('statStreak').textContent=p.streak||0;$('statStars').textContent=p.stars||0;let dc=$('domainCards');dc.innerHTML='';Object.entries(M).forEach(([k,m])=>{let v=acc(k),r=v==null?(k==='sound'||k==='phonics'?'Primary intervention target':k==='meaning'?'Strength — maintain':'Build deliberately'):v>=90?'Secure: maintain with mixed practice':v>=80?'Advance with spaced review':v>=70?'Repeat this domain':'Reduce difficulty and reteach';let x=document.createElement('div');x.className='domain-card';x.innerHTML=`<span>${m[1]}</span><strong>${m[0]}</strong><small>${v==null?'No app data yet':v+'% accuracy'} • ${r}</small><div class="domain-bar"><i style="width:${v||0}%"></i></div>`;dc.appendChild(x)});$('lettersInput').value=p.settings.letters;$('topicInput').value=p.settings.topic;$('vocabInput').value=p.settings.vocab;let t='<table class="progress-table"><thead><tr><th>Week</th><th>Focus</th><th>Complete</th><th>Avg.</th><th>Decision</th></tr></thead><tbody>';T.forEach((x,w)=>{let q=N.map((_,d)=>p.lessons[`${w}-${d}`]).filter(Boolean),n=q.filter(z=>z.done).length,v=q.length?Math.round(q.reduce((s,z)=>s+(z.acc||0),0)/q.length):null;t+=`<tr><td>Week ${w+1}</td><td>${x[0]}</td><td>${n}/5</td><td>${v==null?'—':v+'%'}</td><td>${badge(v)}</td></tr>`});$('parentTableWrap').innerHTML=t+'</tbody></table>'}
$('backBtn').onclick=()=>view('home');$('parentBackBtn').onclick=()=>view('home');$('parentBtn').onclick=()=>view('parent');$('speakBtn').onclick=()=>speak(st.prompt);$('hintBtn').onclick=()=>{$('feedback').textContent=st.hint;$('feedback').className='feedback hint'};$('nextBtn').onclick=next;$('newBridgeBtn').onclick=bridge;$('alignmentForm').onsubmit=e=>{e.preventDefault();p.settings={letters:$('lettersInput').value.trim(),topic:$('topicInput').value.trim(),vocab:$('vocabInput').value.trim()};save();$('settingsSaved').textContent='Saved on this device.';setTimeout(()=>$('settingsSaved').textContent='',1800)};$('resetBtn').onclick=()=>{if(confirm('Reset all Literacy Mission progress and settings on this device?')){p=blank();save();parent();home()}};$('installBtn').onclick=async()=>{if(st.defer){st.defer.prompt();await st.defer.userChoice;st.defer=null}else $('installModal').classList.remove('hidden')};$('closeInstall').onclick=()=>$('installModal').classList.add('hidden');$('installModal').onclick=e=>{if(e.target===$('installModal'))$('installModal').classList.add('hidden')};addEventListener('beforeinstallprompt',e=>{e.preventDefault();st.defer=e});if('serviceWorker' in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('../sw.js').catch(()=>{});home();view('home');
})();
